/*
 * ImagePicker.java
 *
 * Created on July 21, 2006, 1:42 AM
 */

package org.jdesktop.swingx.editors;

/**
 *
 * @author  joshy
 */
public class ImagePicker extends javax.swing.JPanel {
    
    /** Creates new form ImagePicker */
    public ImagePicker() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imageView = new org.jdesktop.swingx.JXImageView();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        imageView.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        add(imageView, gridBagConstraints);

        jButton1.setAction(imageView.getOpenAction());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(jButton1, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.swingx.JXImageView imageView;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}
