/*
 * ShapeChooser.java
 *
 * Created on August 23, 2006, 10:19 PM
 */

package org.jdesktop.swingx.editors;

/**
 *
 * @author  joshy
 */
public class ShapeChooser extends javax.swing.JPanel {
    
    /** Creates new form ShapeChooser */
    public ShapeChooser() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        shapeCombo = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        shapeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Square", "Circle" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        add(shapeCombo, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox shapeCombo;
    // End of variables declaration//GEN-END:variables
    
}
