package org.jdownloader.statistics;

public enum DownloadResult {
    UNKNOWN,
    ACCOUNT_INVALID,
    ACCOUNT_REQUIRED,
    ACCOUNT_UNAVAILABLE,
    CAPTCHA,
    CONDITIONAL_SKIPPED,
    CONNECTION_ISSUES,
    CONNECTION_UNAVAILABLE,
    FAILED,
    FAILED_INCOMPLETE,
    FATAL_ERROR,
    FILE_UNAVAILABLE,
    FINISHED,
    FINISHED_EXISTS,
    HOSTER_UNAVAILABLE,
    IP_BLOCKED,
    OFFLINE_TRUSTED,
    OFFLINE_UNTRUSTED,
    PLUGIN_DEFECT,
    PROXY_UNAVAILABLE,
    SKIPPED

}
