#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/../../src/:$APPDIR/../../bin:gwt-user.jar:gwt-dev-linux.jar:smartgwt.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/output" "$@" jd.plugins.optional.webinterface.gwt.jd;
