//jDownloader - Downloadmanager
//Copyright (C) 2011  JD-Team support@jdownloader.org
//
//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//GNU General Public License for more details.
//
//You should have received a copy of the GNU General Public License
//along with this program.  If not, see <http://www.gnu.org/licenses/>.

package jd.plugins.hoster;

import java.io.IOException;

import jd.PluginWrapper;
import jd.plugins.Account;
import jd.plugins.AccountInfo;
import jd.plugins.DownloadLink;
import jd.plugins.DownloadLink.AvailableStatus;
import jd.plugins.HostPlugin;
import jd.plugins.LinkStatus;
import jd.plugins.PluginException;
import jd.plugins.PluginForHost;

/**
 * The idea behind this is to speed up linkchecking for host providers that go permanently offline. URLs tend to stay cached/archived on the
 * intrawebs longer than host provider. By providing the original plugin regular expression(s) we do not have to rely on directhttp plugin
 * for linkchecking, or surrounding issues with 'silent errors' within the linkgrabber if the file extension isn't matched against
 * directhttp. <br />
 * - raztoki<br />
 * <br />
 * Set interfaceVersion to 3 to avoid old Stable trying to load this Plugin<br />
 *
 * @author raztoki<br />
 */
@HostPlugin(revision = "$Revision$", interfaceVersion = 3,

        names = { "powerwatch.pw", "up4file.com", "sli.mg", "sfshare.se", "rabbitfile.com", "megadysk.pl", "megadrv.com", "grimblr.com", "dwn.so", "cloudshares.net", "72bbb.com", "vip-shared.com", "someimage.com", "rodfile.com", "mightyupload.com", "pornative.com", "oload.net", "mediafire.bz", "lafiles.com", "kure.tv", "junocloud.me", "fileweed.net", "imgmaze.com", "imgblitz.pw", "fibero.co", "filescloud.co", "fileload.io", "dedifile.com", "anysend.com", "2downloadz.com", "otakushare.com", "uploadbb.co", "bitcasa.com", "imgwet.com", "ziddu.com", "imxd.net", "myvideo.de", "timsah.com", "shared.sx", "stagevu.com", "vip-file.com", "shareflare.net", "moevideo.net", "letitbit.net", "lumload.com", "rosharing.net", "erafile.com", "uploading.com", "cloudsix.me", "zalaa.com", "vodlocker.com", "vidbull.com", "timeload.net", "sendspace.pl", "secureupload.eu", "mp3takeout.com", "imzdrop.com",
                "idowatch.net", "jpopsuki.tv", "minus.com", "happystreams.net", "kingload.net", "interfile.net", "imgbb.net", "filemoney.com", "auengine.com", "rocketfiles.net", "flashvids.org", "yamivideo.com", "divxhosted.com", "4upld.com", "filespart.com", "uploadc.com", "skymiga.com", "shareblue.eu", "videopremium.tv", "veterok.tv", "goo.im", "soundowl.com", "megaxfile.com", "fastimg.org", "bitshare.com", "promptfile.com", "fireswap.org", "vessel.com", "loadus.net", "gbload.com", "themediastorage.com", "uphere.pl", "megashares.com",
                /** -> */
                "sockshare.ws", "putlocker.ws", "vodu.ch", "watchfreeinhd.com"/** <- these are all the same site */
                , "vidspot.net", "hzfile.al", "video.tt", "tradingporn.com", "pdfcast.org", "mydisk.ge", "mp3hamster.net", "megacache.net", "laoupload.com", "hoodload.com", "filerev.cc", "filepi.com", "filehoot.com", "maxcloud.xyz", "mediaupload.us", "hugefiles.net", "upvast.com", "allmyvideos.net", "filestorm.xyz", "1tube.to", "hdstream.to", "sendfile.pl", "sharesix.net", "sharesix.com", "filenuke.com", "sharing.zone", "filesabc.com", "sendfiles.nl", "firstplanet.eu", "shareneo.net", "vidxtreme.to", "ugoupload.net", "sharingmaster.com", "hexupload.com", "videomega.tv", "speedyshare.com", "uploadbaz.com", "stiahni.si", "imgbar.net", "voooh.com", "filesuniverse.com", "vodbeast.com", "primephile.com", "hzfile.asia", "axfiles.net", "filenuke.net", "anonfiles.com", "revclouds.com", "upple.it", "filesbomb.in", "livecloudz.com", "uploadscenter.com", "uploadspace.pl", "filebeam.com",
                "bestreams.net", "zettahost.tv", "divxpress.com", "primeshare.tv", "uploadingit.com", "veevr.com", "putstream.com", "zalohuj.to", "yy132.cn", "snakefiles.com", "rapidvideo.tv", "radicalshare.com", "nizfile.net", "novamov.me", "freespace.by", "fastimg.org", "fileflush.com", "downlod.co", "datoteke.com", "animeuploads.com", "cizgifilmlerizle.com", "1000shared.com", "myupload.dk", "vidce.tv", "uploadcoins.com", "fufox.net", "ninjashare.pl", "city-upload.com", "7958.com", "beemp3s.org", "coladrive.com", "megaloads.org", "easydow.org", "easywatch.tv", "vplay.ro", "chayfile.com", "purevid.com", "hdload.info", "devilshare.net", "lolabits.es", "gigafront.de", "5fantastic.pl", "upnito.sk", "copy.com", "treefiles.com", "mrfile.me", "filepurpose.com", "fexe.com", "avht.net", "24uploading.com", "datagrad.ru", "filesup.co", "steepafiles.com", "yourfiles.to", "hotbytez.com",
                "fileover.net", "vipup.in", "terafile.co", "vidig.biz", "uploadmax.net", "soniclocker.com", "ps3gameroom.net", "ipithos.to", "nowvideo.ws", "fileloby.com", "imgsee.me", "jumbofiles.com", "imgmega.com", "fisierulmeu.ro", "filepost.com", "djvv.com", "creeperfile.com", "bleuup.net", "carrier.so", "nosupload.com", "moviesand.com", "vidgrab.net", "netkups.com", "luckyshare.net", "abelhas.pt", "divshare.com", "letitload.com", "uploadsun.com", "cloudcorner.com", "gasxxx.com", "imageporter.com", "jizzbox.com", "foxytube.com", "fileplaneta.com", "nekaka.com", "vipfileshare.com", "filecore.co.nz", "idrivesync.com", "youporn-deutsch.com", "onlinestoragesolution.com", "oooup.com", "anonymousdelivers.us", "watching.to", "vipfile.in", "teraupload.net", "swiftupload.com", "xddisk.com", "xfiles.ivoclarvivadent.com", "vidd.tv", "up2box.co", "storefiles.co", "songs.to", "sharelink.li",
                "nowvideos.eu", "mediaprog.ru", "jumbofile.net", "maxupload.tv", "jippyshare.com", "labload.com", "joinfile.com", "hcbit.com", "gigafileupload.com", "filesin.com", "filekee.com", "fileshost.ws", "fileshare.to", "filenium.com", "filer.cx", "exstorage.net", "fileneo.com", "filemeup.net", "data.cod.ru", "cx.com", "cloudsuzy.com", "foxplay.info", "1gbpsbox.com", "banicrazy.info", "veodrop.com", "bigdownloader.com", "beehd.net", "3files.net", "filehost.pw", "storbit.net", "anyfiles.org", "2upfile.com", "ryushare.com", "onevideo.to", "junkyvideo.com", "filecrash.co", "filearning.com", "xenubox.com", "remixshare.com", "filecloud.cc", "4upfiles.com", "plunder.com", "elffiles.com", "shantibit.com", "x-share.ru", "vinupload.com", "linkfile.de", "jumbofiles.net", "freeporn.to", "filebrella.com", "storedrives.com", "uploadblast.com", "skyvids.net", "4uploaded.com", "up4.im",
                "v-vids.com", "animepremium.tv", "firedrive.com", "sockshare.com", "bearfiles.in", "mooshare.biz", "animecloud.me", "aimini.net", "rainy.la", "project-free-upload.com", "netload.in", "riotshare.com", "premiuns.org", "sendfaile.com", "pururin.com", "tumi.tv", "180upload.com", "tuspics.net", "stageflv.com", "shr77.com", "filebulk.com", "speedy-share.com", "sloozie.com", "otr-download.de", "fizy.com", "1tpan.com", "4uploading.com", "dropvideo.com", "filebox.ro", "vidbux.com", "filerock.net", "movreel.com", "megavideoz.eu", "realvid.net", "blip.tv", "gulfup.com", "hardwareclips.com", "uploadnet.co", "files.gw.kz", "files123.net", "free4share.de", "gettyfile.ru", "free-share.ru", "rziz.net", "zinwa.com", "wuala.com", "fileband.com", "megairon.net", "xfileload.com", "free-uploading.com", "fileown.com", "verzend.be", "rapidsonic.com", "filepack.pl", "goldbytez.com",
                "filemaze.ws", "divxden.com", "vidplay.net", "royalvids.eu", "superromworld.de", "n-roms.de", "simpleshare.org", "sharebeast.com", "sanshare.com", "faststream.in", "storedeasy.com", "jumbofiles.org", "uploadlux.com", "linestorage.com", "thefile.me", "muchshare.net", "queenshare.com", "videobam.com", "mp3the.net", "fileforever.net", "quickshare.cz", "privatehomeclips.com", "warped.co", "played.to", "topupload1.com", "creafile.net", "creafile.com", "krotix.net", "akafile.com", "videonan.com", "uploadbits.net", "upload-drive.com", "share.time.mn", "pushfile.com", "fileriio.com", "dropfiles.info", "2drive.net", "400disk.com", "up-loading.net",
                /** turbobit alias' */
                "sharephile.com", "mxua.com", "katzfiles.com", "fsakura.com", "uploadur.com", "wyslijplik.pl", "tishare.com", "share50.com", "med1fire.com", "dumpfiles.org", "videolog.tv", "storeplace.org", "mojoload.com", "ifilehosting.net", "gigfiles.net", "maxisonic.com", "sv-esload.com", "upgaf.com", "gulfdown.com", "imageeer.com", "loombo.com", "upbrasil.info", "filegig.com", "xtraupload.net", "upservmedia.com", "cloudlync.com", "uploadto.us", "loudupload.net", "minoshare.com", "fun-vids.org", "flowload.com", "divxplanet.com", "saryshare.com", "uploadrive.com", "noelshare.com", "yunio.com", "daj.to", "voowl.com", "filerio.im", "boosterking.com", "u-tube.ru", "medifire.net", "galaxy-file.com", "uploadhunt.com", "upload-il.com", "uploadhero.co", "filefeltolto.hu", "przeslij.net", "altervideo.net", "fileswap.com", "safesharing.eu", "japlode.com", "shared.com", "streamit.to",
                "ilook.to", "imgah.com", "grooveshark.com", "mais.me", "megaul.com", "maxshare.pl", "mcupload.com", "mediavalise.com", "uncapped-downloads.com", "deerfile.com", "fupload.net", "zomgupload.com", "disk.84dm.com", "gfssex.com", "7thsky.es", "2download.de", "filezup.net", "fastupload.org", "files2share.ch", "metfiles.com", "1024disk.com", "boojour.eu", "clips-and-pics.org", "axifile.com", "filedust.net", "mixturecloud.com", "1st-files.com", "gigabyteupload.com", "filespeed.net", "midupload.com", "rainupload.com", "kingshare.to", "mejuba.com", "xlocker.net", "xvideohost.com", "rapidshare.com", "dwnshare.pl", "azerfile.com", "sindema.info", "seenupload.com", "sangfile.com", "fileloads.cc", "wdivx.com", "hotsvideos.com", "lovevideo.tv", "transitfiles.com", "xuploading.net", "asfile.com", "roottail.com", "filehostup.com", "freehostina.com", "porntubevidz.com", "upchi.co.il",
                "fastvideo.eu", "hostingbulk.com", "therapide.cz", "yonzy.com", "ravishare.com", "vozupload.com", "getzilla.net", "videodd.net", "dogefile.com", "nakido.com", "filevice.com", "diskfiles.net", "billionuploads.com", "filebite.cc", "gsinfinite.com", "heaven666.org", "saganfiles.com", "theamateurzone.info", "ultrafile.me", "fileb.ag", "k-files.kz", "clicktoview.org", "xvidstream.net", "filemup.com", "miloshare.com", "lomafile.com", "megacrypter.com", "iiiup.com", "digzip.com", "senseless.tv", "henchfile.com", "cometfiles.com", "mijnbestand.nl", "upafile.com", "bl.st", "filthyrx.com", "turbovid.net", "privatefiles.com", "vacishare.com", "xerver.co", "qshare.com", "tuxfile.com", "gigaup.fr", "hddspace.com", "foxishare.com", "filestube.com", "miloyski.com", "upload.hidemyass.com", "divxhosting.net", "sube.me", "quickupload.net", "mydisc.net", "isavelink.com", "filestorm.to",
                "cruzload.com", "bubblefiles.com", "dodane.pl", "bayfiles.net", "myuplbox.com", "updown.bz", "thefilebay.com", "mukupload.com", "box4up.com", "5ilthy.com", "filepom.com", "dizzcloud.com", "cloudfly.us", "vidhog.com", "slingfile.com", "iperupload.com", "oceanus.ch", "mrmkv-fileshare.com", "filejungle.com", "fileserve.com", "zalil.ru", "uploadsat.com", "turbotransfer.pl", "uploadlab.com", "shareyourfile.biz", "tomwans.com", "megabox.ro", "failai.kava.lt", "stahovadlo.cz", "justin.tv", "4share.ws", "pliczek.net", "2gb-hosting.com", "maskfile.com", "rockdizfile.com", "yesload.net", "dotsemper.com", "mixbird.com", "myjizztube.com", "packupload.com", "megaszafa.com", "potload.com", "usefile.com", "nitrobits.com", "uploads.center", "filemonkey.in", "multishared.me", "wallbase.cc", "swankshare.com", "vidbox.yt", "vidzbeez.com", "megafiles.se", "fileom.com", "bluehaste.com",
                "socifiles.com", "mlfat4arab.com", "megashare.by", "flinzy.com", "filesend.net", "fastfileshare.com.ar", "ddlstorage.com", "spaadyshare.com", "sizfile.com", "hostingcup.com", "filecanyon.com", "bytesbox.com", "dropvideos.net", "tubecloud.net", "xrabbit.com", "tubeq.net", "multiupload.com", "pizzaupload.com", "ntupload.com", "magnovideo.com", "files.to", "moidisk.ru", "vidaru.com", "epicshare.net", "filemov.net", "hipfile.com", "zingload.com", "fileove.com", "rnbload.com", "filesaur.com", "wrzuc.to", "hyshare.com", "redload.net", "blitzfiles.com", "qkup.net", "lajusangat.net", "filechum.com", "uploadnetwork.eu", "videoslim.net", "filesfrog.net", "fiberupload.net", "hottera.com", "filego.org", "putme.org", "upshare.me", "uploadzeal.com", "space4file.com", "mangatraders.com", "nzbload.com", "vreer.com", "safashare.com", "shareprofi.com", "crisshare.com", "lemuploads.com",
                "pandapla.net", "finaload.com", "shurload.es", "megaupdown.com", "imagehaven.net", "filedap.com", "limevideo.net", "vids.bz", "wallobit.com", "davvas.com", "uploadinc.com", "filelaser.com", "finaload.com", "hostinoo.com", "sinhro.net", "megashare.com", "berofile.com", "uploadizer.net", "megarelease.org", "share-byte.net", "rapidstation.com", "filechin.com", "fujifile.me", "freeuploads.fr", "guizmodl.net", "file1.info", "maximusupload.com", "pandamemo.com", "igetfile.com", "megacloud.com", "egofiles.com", "dupload.net", "cloudvidz.net", "videozed.net", "donevideo.com", "migaload.com", "maxvideo.pl", "tgf-services.com", "albafile.com", "cramit.in", "4savefile.com", "batshare.com", "oleup.com", "rapidstone.com", "filecopter.net", "easyfilesharing.info", "uploadedhd.com", "ilikefile.com", "fileomg.com", "file.am", "navihost.us", "upfile.biz", "dynaupload.com", "freevideo.cz",
                "file-speed.com", "cloudxeon.com", "hdplay.org", "files2upload.net", "dollyshare.com", "filetug.com", "mirorii.com", "fucktube.com", "faceporn.no", "bitload.it", "beatplexity.com", "bandbase.dk", "bananahost.it", "gigamax.ch", "goldfile.eu", "judgeporn.com", "elcorillord.org", "rocketfile.net", "maxisharing.com", "duckload.co", "homesexdaily.com", "pornbanana.com", "celebritycunt.net", "speedvid.tv", "filexb.com", "upsharez.com", "universalfilehosting.com", "4vid.me", "anyap.info", "evominds.com", "topvideo.cc", "zenfiles.biz", "fryhost.com", "turtleshare.com", "uploadjet.net", "devilstorage.com", "videofox.net", "extabit.com", "videofrog.eu", "nirafile.com", "omploader.org", "speedload.org", "sharefiles.co", "upit.in", "dump1.com", "fleon.me", "limelinx.com", "flashstream.in", "hotuploading.com", "filecity.net", "servifile.com", "filegag.com", "sharerun.com",
                "heftyfile.com", "uploadorb.com", "clipshouse.com", "edoc.com", "fileswappr.com", "filerace.com", "cloudzer.net", "netdrive.ws", "file4sharing.com", "rapidapk.com", "docyoushare.com", "kongsifile.com", "vureel.com", "dataport.cz", "uploadoz.com", "warserver.cz", "1clickshare.net", "cepzo.com", "fireuploads.net", "megaup1oad.net", "megaup.me", "ezzfile.com", "skylo.me", "filefolks.com", "videoslasher.com", "filebigz.com", "filezy.net", "vidx.to", "uploadstation.com", "wooupload.com", "ifile.ws", "filesbb.com", "ihostia.com", "youload.me", "ok2upload.com", "bitupload.com", "cobrashare.sk", "enjoybox.in", "share4files.com", "up.msrem.com", "megaload.it", "terafiles.net", "freestorage.ro", "filekai.com", "divxforevertr.com", "filekeeping.de", "livefile.org", "iranfilm16.com", "isharemybitch.com", "shufuni.com", "belgeler.com", "loadhero.net", "ngsfile.com",
                "1-clickshare.com", "fastsonic.net", "brutalsha.re", "moviesnxs.com", "hotfile.com", "sharedbit.net", "ufox.com", "comload.net", "6ybh-upload.com", "cloudnes.com", "fileprohost.com", "cyberlocker.ch", "filebox.com", "x7files.com", "videozer.com", "megabitshare.com", "filestay.com", "uplly.com", "asixfiles.com", "zefile.com", "kingsupload.com", "fileking.co", "sharevid.co", "4fastfile.com", "1-upload.com", "dump.ro", "dippic.com", "uploking.com", "zshare.ma", "book-mark.net", "ginbig.com", "ddl.mn", "syfiles.com", "iuploadfiles.com", "thexyz.net", "zakachali.com", "indianpornvid.com", "hotfiles.ws", "wizzupload.com", "banashare.com", "downupload.com", "putshare.com", "vidbox.net", "filetube.to", "nowveo.com", "uploadic.com", "flashdrive.it", "flashdrive.uk.com", "filewinds.com", "wrzucaj.com", "yourfilestorage.com", "toucansharing.com", "uploaddot.com", "zooupload.com",
                "uploadcore.com", "spaceha.com", "tubethumbs.com", "peeje.com", "datacloud.to", "xxxmsncam.com", "uploadboxs.com", "247upload.com", "fileshare.in.ua", "upload.tc", "filesmall.com", "fileuplo.de", "quakefile.com", "wupfile.com", "vdoreel.com", "flazhshare.com", "upmorefiles.com", "cloudyload.com", "icyfiles.com", "vidpe.com", "clouds.to", "zuzufile.com", "hostfil.es", "onlinedisk.ru", "fileduct.com", "frogup.com", "filejumbo.com", "dump.ru", "fileshawk.com", "vidstream.us", "filezpro.com", "fileupper.com", "speedy-share.net", "files.ge", "gbitfiles.com", "xtilourbano.info", "allbox4.com", "arab-box.com", "farmupload.com", "filedefend.com", "filesega.com", "kupload.org", "multishare.org", "98file.com", "wantload.com", "esnips.com", "uload.to", "share76.com", "filemates.com", "stahnu.to", "filestock.ru", "uploader.pl", "mach2upload.com", "megaunload.net", "bonpoo.com",
                "modovideo.com", "bitoman.ru", "maknyos.com", "upgrand.com", "pigsonic.com", "filevelocity.com", "filegaze.com", "ddldrive.com", "fileforth.com", "files-save.com", "media-4.me", "backupload.net", "upafacil.com", "filedownloads.org", "filesector.cc", "netuploaded.com", "squillion.com", "sharebees.com", "filetobox.com", "mojedata.sk", "grupload.com", "stickam.com", "gimmedatnewjoint.com", "dup.co.il", "eazyupload.net", "depoindir.com", "own3d.tv", "drop.st", "favupload.com", "anonstream.com", "odsiebie.pl", "shareupload.com", "filebeer.info", "uploadfloor.com", "venusfile.com", "welload.com", "upaj.pl", "shareupload.net", "tsarfile.com", "omegave.org", "fsx.hu", "kiwiload.com", "gbmeister.com", "filesharing88.net", "fileza.net", "filecloud.ws", "filesome.com", "filehost.ws", "filemade.com", "bloonga.com", "zettaupload.com", "aavg.net", "freeporn.com", "bitbonus.com",
                "sharebeats.com", "vidhost.me", "filetechnology.com", "badongo.com", "uptorch.com", "videoveeb.com", "fileupped.com", "repofile.com", "filemsg.com", "dopeshare.com", "filefat.com", "fileplayground.com", "fileor.com", "aieshare.com", "q4share.com", "share-now.net", "1hostclick.com", "mummyfile.com", "hsupload.com", "upthe.net", "ufile.eu", "bitroad.net", "coolshare.cz", "speedfile.cz", "your-filehosting.com", "brontofile.com", "filestrum.com", "filedove.com", "sharpfile.com", "filerose.com", "filereactor.com", "boltsharing.com", "turboupload.com", "glumbouploads.com", "terabit.to", "buckshare.com", "zeusupload.com", "filedino.com", "filedude.com", "uptal.org", "uptal.net", "file-bit.net", "xtshare.com", "cosaupload.org", "sharing-online.com", "filestrack.com", "shareator.net", "azushare.net", "filecosy.com", "monsteruploads.eu", "vidhuge.com", "doneshare.com", "cixup.com",
                "animegoon.com", "supermov.com", "ufliq.com", "vidreel.com", "deditv.com", "supershare.net", "shareshared.com", "uploadville.com", "fileserver.cc", "bebasupload.com", "savefile.ro", "ovfile.com", "divxbase.com", "gptfile.com", "dudupload.com", "eyvx.com", "farshare.to", "azsharing.com", "freefilessharing.com", "elitedisk.com", "freakmov.com", "cloudnator.com", "filesavr.com", "saveufile.in.th", "migahost.com", "fastfreefilehosting.com", "files2k.eu", "shafiles.me", "jalurcepat.com", "divload.org", "refile.net", "oron.com", "wupload.com", "filesonic.com", "xxlupload.com", "cumfox.com", "pyramidfiles.com", "nahraj.cz", "jsharer.com", "annonhost.net", "filekeeper.org", "dynyoo.com", "163pan.com", "imagehost.org", "4us.to", "yabadaba.ru", "madshare.com", "diglo.com", "tubeload.to", "tunabox.net", "yourfilehost.com", "uploadegg.com", "brsbox.com", "amateurboobtube.com",
                "good.net", "freeload.to", "netporn.nl", "przeklej.pl", "alldrives.ge", "allshares.ge", "holderfile.com", "megashare.vnn.vn", "link.ge", "up.jeje.ge", "up-4.com", "cloudcache", "ddlanime.com", "mountfile.com", "platinshare.com", "megavideo.com", "megaupload.com", "megaporn.com", "zshare.net", "uploading4u.com", "megafree.kz", "batubia.com", "upload24.net", "files.namba.kz", "datumbit.com", "fik1.com", "fileape.com", "filezzz.com", "imagewaste.com", "fyels.com", "gotupload.com", "sharehub.com", "sharehut.com", "filesurf.ru", "openfile.ru", "letitfile.ru", "tab.net.ua", "uploadbox.com", "supashare.net", "usershare.net", "skipfile.com", "10upload.com", "x7.to", "uploadking.com", "uploadhere.com", "fileshaker.com", "vistaupload.com", "groovefile.com", "enterupload.com", "xshareware.com", "xun6.com", "yourupload.de", "youshare.eu", "mafiaupload.com", "addat.hu", "archiv.to",
                "bigupload.com", "biggerupload.com", "bitload.com", "bufiles.com", "cash-file.net", "combozip.com", "duckload.com", "exoshare.com", "file2upload.net", "filebase.to", "filebling.com", "filecrown.com", "filefrog.to", "filefront.com", "filehook.com", "filestage.to", "filezup.com", "fullshare.net", "gaiafile.com", "keepfile.com", "kewlshare.com", "lizshare.net", "loaded.it", "loadfiles.in", "megarapid.eu", "megashare.vn", "metahyper.com", "missupload.com", "netstorer.com", "nextgenvidz.com", "piggyshare.com", "profitupload.com", "quickload.to", "quickyshare.com", "share.cx", "sharehoster.de", "shareua.com", "speedload.to", "upfile.in", "ugotfile.com", "upload.ge", "uploadmachine.com", "uploady.to", "uploadstore.net", "vspace.cc", "web-share.net", "yvh.cc", "x-files.kz", "oteupload.com" },

        urls = { "https?://(?:www\\.)?powerwatch\\.pw/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?up4file\\.com/[A-Za-z0-9]+", "https?://(?:www\\.)?sli\\.mg/[A-Za-z0-9]+", "https?://(www\\.)?sfshare\\.se/[a-z0-9]{12}", "http://(www\\.)?rabbitfile\\.com/(download_regular\\.php\\?file=|dl\\.php\\?f=)[A-Za-z0-9]+", "https?://(?:www\\.)?megadysk\\.pl/(f|s)/[A-Za-z0-9\\.]+(?:/n/[^/]+)?", "http://(?:www\\.)?megadrv\\.com/.+", "https?://(?:www\\.)?grimblr\\.com/[A-Za-z0-9]+", "http://(www\\.)?(dwn\\.so/show\\-file/[a-z0-9]+/\\d+/[^<>\"/]+\\.html|st\\.dwn\\.so/v/[A-Z0-9]+)", "https?://(www\\.)?cloudshares\\.net/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?72bbb\\.com/(?:file|view)\\-\\d+\\.html", "https?://(?:www\\.)?vip\\-shared\\.com/[A-Za-z0-9]+", "https?://someimage\\.com/([^<>\"]+)", "https?://(www\\.)?rodfile\\.com/(vidembed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?mightyupload\\.com/((vid)?embed\\-)?[a-z0-9]{12}(?:/\\S+)?", "http://(www\\.)?pornative\\.com/\\d+\\.html", "https?://(?:www\\.)?oload\\.net/(?:embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?mediafire\\.bz/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?lafiles\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?kure\\.tv/.+", "https?://(\\w+\\.)?junocloud\\.me/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?fileweed\\.net/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?imgmaze\\.com/(?:embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?imgblitz\\.pw/(?:embed\\-)?[a-z0-9]{12}", "http://(?:www\\.)?fibero\\.co/download/[a-z0-9\\-]+", "https?://(?:www\\.)?filescloud\\.co/(?:embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?fileload\\.io/[A-Za-z0-9]+(/[^/]+)?", "https?://(?:www\\.)?dedifile\\.com/(?:embed\\-)?[a-z0-9]{12}",
                "http://(www\\.)?anysend\\.com/[A-F0-9]{32}", "https?://(www\\.)?2downloadz\\.com/[a-z0-9]+", "https?://(?:www\\.)?otakushare\\.com/.+", "https?://(?:www\\.)?uploadbb\\.co/.+", "https?://(?:[a-z0-9]+\\.)?bitcasa\\.com/.+", "https?://(?:www\\.)?imgwet\\.com/img\\-[a-z0-9]+\\.html", "https?://(?:www\\.)?ziddu\\.com/.+", "https?://(?:www\\.)?imxd\\.(?:net|us)/.+", "https?://(?:www\\.)?myvideo\\.de/.+", "https?://(?:www\\.)?timsah\\.com/.+", "https?://(?:www\\.)?shared\\.sx/.+", "https?://(?:www\\.)?stagevu\\.com/.+", "https?://(?:www\\.)?vip\\-file\\.com/.+", "https?://(?:www\\.)?shareflare\\.net/.+", "https?://(?:www\\.)?(?:(?:moevideos|moevideo|videochart)\\.net|playreplay\\.me)/.+", "https?://(?:www\\.)?letitbit\\.net/.+", "https?://(www\\.)?lumload\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?(?:rosharing\\.com|rosharing\\.net|roshare\\.info)/[A-Za-z0-9]+",
                "https?://(?:www\\.)?erafile\\.com/(?:embed\\-)?[a-z0-9]{12}", "http://(www\\.)?uploading\\.com/(files/get/[A-Za-z0-9]+|\\w+/\\w+)", "https?://(www\\.)?cloudsix\\.me/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?zalaa\\.com/[a-z0-9]{12}", "https?://(?:www\\.)?vodlocker\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?vidbull\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?timeload\\.net/(?:embed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?sendspace\\.pl/file/[\\w]+/?", "https?://(www\\.)?secureupload\\.eu/[a-z0-9]{12}", "http://(www\\.)?mp3takeout\\.com/download\\.php\\?file=[A-Za-z0-9\\-_\\.]+", "https?://(www\\.)?imzdrop\\.com/(?:embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?idowatch\\.net/(?:embed\\-)?[a-z0-9]{12}", "http://(www\\.)?jpopsuki\\.tv/video/[^<>\"]+",
                "http://([a-zA-Z0-9]+\\.)?(minus\\.com|min\\.us)/[A-Za-z0-9]{2,}((?:_[a-z]{1,2})?\\.(?:bmp|png|jpe?g|gif))?", "https?://(www\\.)?happystreams\\.net/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?kingload\\.net/[A-Za-z0-9]+", "https?://(www\\.)?interfile\\.net/((vid)?embed\\-)?[a-z0-9]{12}", "http://(?:www\\.)?imgbb\\.net/v\\-.+", "https?://(www\\.)?filemoney\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?auengine\\.(?:com|io)/(embed\\.php\\?file=.+|embed/[a-zA-Z0-9]+)", "http://(www\\.)?rocketfiles\\.net/video/[a-z0-9]+", "http://(www\\.)?flashvids\\.org/video/[a-z0-9]+", "http://(www\\.)?yamivideo\\.com/video/[a-z0-9]+", "http://(www\\.)?divxhosted\\.com/video/[a-z0-9]+", "https?://(www\\.)?4upld\\.com/[A-Za-z0-9]+", "http://(www\\.)?filespart\\.com/(dl|go)/[0-9a-zA-Z]+\\.html", "https?://(?:www\\.)?uploadc\\.(?:com|ch)/(?:vidembed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?skymiga\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?shareblue\\.eu/[a-z0-9]+", "https?://(www\\.)?videopremium\\.(net|tv|me)/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?veterok\\.tv/(video|v)/\\d+", "https?://(www\\.)?goo\\.im/[^<>\"]+", "https?://(?:www\\.)?soundowl\\.com/track/[a-z0-9]+|http://dl\\.soundowl\\.com/[a-z0-9]+\\.mp3", "https?://(www\\.)?megaxfile\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?fastimg\\.org/(?:enter|thumbnail|original)/[a-f0-9]{16}", "http://(www\\.)?bitshare\\.com/(\\?(f|m)=[a-z0-9]{8}|files/[a-z0-9]{8})", "http://(www\\.)?promptfile\\.com/l/[A-Z0-9]+\\-[A-Z0-9]+", "https?://(www\\.)?fireswap\\.org/(embed\\-)?[a-z0-9]{12}", "https?://www\\.vessel\\.com/(?:news/)?videos/[A-Za-z0-9\\-]+", "https?://(?:www\\.)?loadus\\.net/(?:embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?gbload\\.com/[A-Za-z0-9]+",
                "https?://(www\\.)?(thefileupload|themediastorage)\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?uphere\\.pl/\\?v=[a-z0-9]{32}", "http://[\\w\\.]*?(d[0-9]{2}\\.)?megashares\\.com/(.*\\?d[0-9]{2}=[0-9a-zA-Z]{7}|dl/[0-9a-zA-Z]{7}/)", "http://(www\\.)sockshare\\.ws/file/[A-Za-z0-9]+", "http://(www\\.)?putlocker\\.ws/file/[A-Z0-9]+", "http://(www\\.)?vodu\\.ch/file/[a-f0-9]{32}/?", "http://(www\\.)?watchfreeinhd\\.(com|org)/[A-Za-z0-9]+", "https?://(www\\.)?vidspot\\.net/((vid)?embed-|builtin-)?[a-z0-9]{12}", "https?://(?:www\\.)?hzfile\\.(?:al|asia)/(?:embed\\-)?[a-z0-9]{12}", "http://(www\\.)?video\\.tt/(watch_video\\.php\\?v=|video/|e/)[A-Za-z0-9]+", "https?://(www\\.)?tradingporn\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?pdfcast\\.org/(pdf|download)/[A-Za-z0-9\\-]+", "http://[\\w\\.]*?mydisk\\.ge/download\\.php\\?id=[A-Z0-9]+",
                "http://(www\\.)?mp3hamster\\.net/(files\\.php\\?eq=[A-Za-z0-9%]+|dll2/.+)", "https?://(www\\.)?megacache\\.net/[a-z0-9]{12}", "https?://(www\\.)?laoupload\\.com/[A-Za-z0-9]{12}/[^<>\"]+\\.html", "http://(www\\.)?(gupload\\.biz|hoodload\\.com)/[a-z0-9]+", "https?://(www\\.)?filerev\\.cc/(?:embed\\-)?[a-z0-9]{12}", "http://(www\\.)?filepi\\.com/i/[A-Za-z0-9]+", "https?://(www\\.)?filehoot\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?maxcloud\\.xyz/[A-Za-z0-9]+", "https?://(?:www\\.)?mediaupload\\.us/(?:embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?hugefiles\\.net/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?(?:upvast\\.com|nornar\\.com|filewe\\.com)/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?allmyvideos\\.net/((?:embed-)?[a-z0-9]{12}|v/v\\-[A-Za-z0-9]+)", "https?://(?:www\\.)?filestorm\\.xyz/[A-Za-z0-9]+", "https?://(?:www\\.)?1tube\\.to/.+",
                "https?://(?:www\\.)?hdstream\\.to/.+", "http://(www\\.)?sendfile\\.pl/\\d+/", "https?://(www\\.)?sharesix\\.net/[a-z0-9]{12}", "https?://(www\\.)?sharesix\\.com/([a-z0-9]{12}|f/[A-Za-z0-9]+)", "https?://(www\\.)?filenuke\\.com/([a-z0-9]{12}|f/[A-Za-z0-9]+)", "https?://(?:www\\.)?sharing\\.zone/[A-Za-z0-9]+", "https?://(www\\.)?filesabc\\.com/[a-z0-9]{12}", "http://(www\\.)?sendfiles\\.nl/download\\.aspx\\?ID=[a-z0-9\\-]+", "http://(?:www\\.)?firstplanet\\.eu/file/\\d+/[a-z0-9\\-]+", "https?://(www\\.)?shareneo\\.net/[A-Za-z0-9]+", "https?://(www\\.)?vidxtreme\\.to/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?ugoupload\\.net/[A-Za-z0-9]+", "https?://(www\\.)?sharingmaster\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?hexupload\\.com/(vidembed\\-)?[a-z0-9]{12}",
                "http://(www\\.)?videomega\\.tv/(?:(?:(?:iframe|cdn|view)\\.php)?\\?ref=|validatehash\\.php\\?hashkey=)[A-Za-z0-9]+", "http://www(\\d+)?\\.speedyshare\\.com/remote/[A-Za-z0-9]+/d\\d+\\-[A-Za-z0-9]+|http://(www\\.)?(speedyshare\\.com|speedy\\.sh)/(files?/)?[A-Za-z0-9]+", "https?://(www\\.)?uploadbaz\\.com/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?(stiahni|stahni)\\.si/((de|en|hu|pl|sk)/)?file/[A-Za-z0-9]+(/.{1})?", "http://(www\\.)?imgbar\\.net/img\\-\\d+\\.html", "https?://(www\\.)?voooh\\.com/[A-Za-z0-9]+", "https?://(www\\.)?filesuniverse\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?vodbeast\\.com/(?:embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?primephile\\.com/[A-Za-z0-9]+", "https?://(?:www\\.)?hzfile\\.(?:com|asia)/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?axfiles\\.net/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?filenuke\\.net/[a-f0-9]{32}",
                "https://(www\\.)?anonfiles\\.com/file/[a-z0-9]{32}", "https?://(www\\.)?revclouds\\.com/(?:embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?upple\\.it/[A-Za-z0-9]+", "https?://(www\\.)?filesbomb\\.in/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?livecloudz\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?uploadscenter\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?uploadspace\\.pl/plik[a-zA-Z0-9]+(/.+)?\\.htm", "http://(www\\.)?(filebeam\\.com/[a-z0-9]{32}|fbe\\.am/[A-Za-z0-9]+)", "https?://(www\\.)?bestreams\\.net/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?zettahost\\.tv/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?divxpress\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?primeshare\\.tv/download/[A-Z0-9]+", "http://(www\\.)?uploadingit\\.com/((d/|get/)[A-Z0-9]{16}|file/(view/|download/)?[a-zA-Z0-9]{16}/.{1})",
                "http://(www\\.)?veevr\\.com/(embed|videos)/[a-zA-Z0-9\\_\\-]+", "https?://(www\\.)?putstream\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?zalohuj\\.to/[A-Za-z0-9]+", "http://(www\\.)?yy132\\.cn/guan/p/\\d+\\.html", "https?://(www\\.)?snakefiles\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?rapidvideo\\.(?:tv|org)/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?radicalshare\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?nizfile\\.net/(?:embed\\-)?[a-z0-9]{12}", "http://(www\\.)?novamov\\.me/video/[a-z0-9]+", "http://[\\w\\.]*?freespace\\.by/download/[a-z0-9]+", "https?://(?:www\\.)?fastimg\\.org/(?:enter|thumbnail|original)/[a-f0-9]{16}", "http://(www\\.)?fileflush\\.com/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es|de)/)?file/[0-9]+/)", "http://(www\\.)?downlod\\.co/file/[a-z0-9]+", "https?://(?:www\\.)?datoteke\\.com/[A-Za-z0-9]+",
                "http://(www\\.)?animeuploads\\.com/embed\\.php\\?file=.+", "http://(www\\.)?cizgifilmlerizle\\.com/embed\\.php\\?file=.+", "https?://(www\\.)?1000shared\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?myupload\\.dk/.+", "https?://(www\\.)?vidce\\.tv/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?uploadcoins\\.com/(?:embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?fufox\\.(?:com|net)/dl/[A-Za-z0-9]{14}", "https?://(?:www\\.)?ninjashare\\.pl/.+", "https?://(?:www\\.)?city\\-upload\\.com/(?:embed\\-)?[a-z0-9]{12}", "https?://(?!www\\.)[a-z0-9]+\\.7958\\.com/.+", "https?://(?:www\\.)?beemp3s\\.org/.+", "http://(www\\.)?(?:colafile|colayun|coladrive)\\.com/file/\\d+", "https?://(www\\.)?megaloads\\.org/(?:embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?easydow\\.(?:com|org)/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?easywatch\\.tv/(embed\\-)?[a-z0-9]{12}",
                "https?://(?:(?:www\\.)?vplay\\.ro/.+|i\\.vplay\\.ro/.+)", "https?://(www\\.)?chayfile\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?purevid\\.com/.+", "https?://(www\\.)?hdload\\.info/(?:embed\\-)?[a-z0-9]{12}", "https?://devilshare\\.net/.+", "http://([a-z0-9]+\\.)?lolabits\\.es/.+", "https?://(?:www\\.)?gigafront\\.de/.+", "http://(?:www\\.)?5fantastic\\.pl/.+", "http://[\\w\\.]*?upnito\\.sk/.+", "https?://(www\\.)?copy\\.com/[^<>\"]+", "https?://(www\\.)?((treefiles|treesfile|trefiles)\\.com|treefile\\.org)/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?mrfile\\.(?:me|co)/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?filepurpose\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?fexe\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?(?:avht|tosix)\\.net/[A-Za-z0-9]+", "https?://(www\\.)?24uploading\\.com/(embed\\-)?[a-z0-9]{12}",
                "http://[a-zA-Z-0-9.]{0,}datagrad.ru/download/[0-9]{1,}", "https?://(?:www\\.)?filesup\\.co/(?:embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?steepafiles\\.com/[A-Za-z0-9]+", "http://[\\w\\.]*?yourfiles\\.(biz|to)/\\?d=[\\w]+", "https?://(www\\.)?hotbytez\\.com/(?:embed\\-)?[a-z0-9]{12}", "http(s)?://(www\\.)?fileover\\.net/\\d+", "https?://(?:www\\.)?vipup\\.in/[A-Za-z0-9]+", "https?://(www\\.)?(terafile\\.co|lumfile\\.(com|se|eu))/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?vidig\\.biz/((vid)?embed\\-)?[a-z0-9]{12}", "http://(www\\.)?uploadmax\\.net/file/[a-z0-9]+", "https?://(www\\.)?soniclocker\\.com/(embed\\-)?[a-z0-9]{12}", "^http://(?:www\\.)?ps3gameroom\\.net/[a-zA-Z0-9]+$", "https?://(www\\.)?ipithos\\.to/(?:embed\\-)?[a-z0-9]{12}", "http://(www\\.)?nowvideo\\.ws/video/[a-z0-9]+", "https?://(www\\.)?fileloby\\.com/[A-Za-z0-9]+",
                "https?://(www\\.)?imgsee\\.me/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?jumbofiles\\.com/[0-9a-z]{12}", "https?://(www\\.)?imgmega\\.com/(embed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?fisierulmeu\\.ro/.+/.+\\.html", "https?://(www\\.)?(filepost\\.com/files|fp\\.io)/[a-z0-9]+", "http://(www\\.)?djvv\\.com/donw_0_\\d+\\.html", "http://(www\\.)?creeperfile\\.(com|net)/[A-Za-z0-9]+", "https?://(?:www\\.)?bleuup\\.(?:com|net)/[A-Za-z0-9]+", "https?://(www\\.)?carrier\\.so/[a-z0-9]{12}", "https?://(www\\.)?nosupload\\.com/(\\?d=)?[a-z0-9]{12}", "http://(www\\.)?moviesand\\.com/(videos/\\d+/[a-z0-9\\-_]+\\.html|embedded/\\d+)", "https?://(?:www\\.)?vidgrab\\.net/.+", "http://(www\\.)?netkups\\.com/\\?(d|play)=[a-z0-9]+", "http://(www\\.)?luckyshare\\.net/\\d+", "https?://(?:www\\.)?abelhas\\.pt/.+", "https?://(?:www\\.)?divshare\\.com/.+",
                "https?://(www\\.)?letitload\\.com/[A-Za-z0-9]+", "https?://(?:www\\.)?uploadsun\\.com/[A-Za-z0-9]+", "https?://(?:www\\.)?cloudcorner\\.com/file/[a-f0-9]{32}", "http://(?:www\\.)?gasxxx\\.com/(?:video/|media/player/config\\.php\\?vkey=)\\d+", "http://(?:www\\.)?(?:imageporter\\.com/[a-z0-9]{12}|img\\d+\\.imageporter\\.com/i/\\d+/[a-z0-9]{12})", "http://(www\\.)?jizzbox\\.com/movies/\\d+\\-[a-z0-9\\-_]+\\.html", "http://(?:www\\.)?foxytube\\.com/(?:videos/\\d+/[a-z0-9\\-]+\\.html|embedded/\\d+)", "https?://(www\\.)?(fileplanet\\.com\\.ua|fileplaneta\\.com)/[a-z0-9]{12}", "https?://(www\\.)?nekaka\\.com/d/[a-zA-Z0-9\\-\\_]{10}", "https?://(www\\.)?vipfileshare\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?(filecore\\.co\\.nz|filecore\\.co|fcore\\.eu)/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?idrivesync\\.com/share/view\\?k=[A-Za-z0-9]+",
                "http://(www\\.)?youporn\\-deutsch\\.com/video/\\d+", "https://free\\.ols18\\.com/data/public/[a-z0-9]+\\.php", "https?://(www\\.)?oooup\\.com/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?anonymousdelivers\\.us/\\d+", "https?://(www\\.)?watching\\.to/(embed\\-|watch/|external/)?[A-Za-z0-9]{12}", "https?://(www\\.)?vipfile\\.in/[A-Za-z0-9]+", "https?://(?:www\\.)?teraupload\\.net/[A-Za-z0-9]+", "https?://(www\\.)?swiftupload\\.com/[A-Za-z0-9]+", "http://(www\\.)?xddisk\\.com/file\\-\\d+\\.html", "https?://(www\\.)?xfiles\\.ivoclarvivadent\\.com/[a-z0-9]{12}", "https?://(www\\.)?vidd\\.tv/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?up2box\\.co/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?storefiles\\.co/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?songs\\.to/([a-z0-9\\-]+/|#(!|%21)pl=)[a-z0-9]{40}", "https?://(www\\.)?sharelink\\.li/(vidembed\\-)?[a-z0-9]{12}",
                "http://(www\\.)?nowvideos\\.eu/video/\\d+/", "https?://(?:www\\.)?mediaprog\\.ru/.+", "https?://(www\\.)?jumbofile\\.net/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?maxupload\\.tv/(file|e)/[A-Za-z0-9]+", "https?://(www\\.)?jippyshare\\.com/[a-z0-9]{12}", "https?://(www\\.)?labload\\.com/[A-Za-z0-9]+", "https?://(www\\.)?joinfile\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?hcbit\\.com/[A-Za-z0-9]+", "https?://(www\\.)?(gigafileupload|gigauploader)\\.com/(file|download)/[^<>\"/]+", "http://(www\\.)?filesin\\.com/[A-Z0-9]+/download\\.html", "https?://(www\\.)?filekee\\.com/[A-Za-z0-9]+", "https?://(www\\.)?fileshost\\.ws/[a-z0-9]{12}", "http://(www\\.)?fileshare\\.to/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(\\w+\\.)?filenium\\.com/get/\\w+/.+", "http://[\\w\\.]*?filer.cx/file/\\d+/[0-9a-zA-Z-.]+",
                "http://(www\\.)?exstorage\\.net/download/[a-z0-9]+", "https?://(www\\.)?fileneo\\.com/[a-z0-9]{12}", "http://(www\\.)?filemeup\\.net/[a-z0-9]+", "http://[a-zA-Z.]{0,}data.cod.ru/[0-9]{1,}", "https://(www\\.)?cx\\.com/mycx/share/[A-Za-z0-9\\-_]+/.{1}", "https?://(www\\.)?cloudsuzy\\.com/[A-Za-z0-9]+", "http://(www\\.)?foxplay\\.info/preloader/[A-Za-z0-9=]+?/", "https?://(?:www\\.)?1gbpsbox\\.com/[A-Za-z0-9]+", "http://(www\\.)?banicrazy\\.info/[a-z0-9]{12}", "https?://(www\\.)?veodrop\\.com/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?bigdownloader\\.com/dl/[a-z0-9]+", "https?://(www\\.)?beehd\\.net/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?3files\\.net/(?:embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?filehost\\.pw/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?(?:uploads\\.xxx|streambit\\.tv|storbit\\.net)/(?:video|file)/[A-Za-z0-9\\-_]+/",
                "https?://(www\\.)?anyfiles\\.org/[A-Za-z0-9]+", "http://(www\\.)?2upfile\\.com/(?!faq|register|login|terms|report_file|plugins)[a-z0-9]+", "https?://(www\\.)?ryushare\\.com/((vid)?embed\\-)?[a-z0-9]{10,12}", "https?://(?:www\\.)?onevideo\\.to/(?:v/|embed\\.php\\?id=)[a-z0-9]+", "https?://(www\\.)?junkyvideo\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?(filecrash\\.co)/[a-z0-9]{12}(?:/[^<>\"/]+)?", "http://(www\\.)?filearning\\.com/(files|get)/[A-Za-z0-9]+\\.html", "https?://(www\\.)?xenubox\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?remixshare\\.com/(.*?\\?file=|download/|dl/)[a-z0-9]+", "https?://(www\\.)?filecloud\\.cc/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?(4upfiles\\.com|4up\\.(im|me))/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?plunder\\.com/[^<>\"/]+(/[^<>\"/]+/)?", "https?://(www\\.)?elffiles\\.com/(embed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?shantibit\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?x\\-share\\.ru/[A-Za-z0-9]+", "https?://(www\\.)?vinupload\\.com/(embed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?linkfile.de/download-[\\w]+\\.php", "https?://(www\\.)?jumbofiles\\.net/[A-Za-z0-9]+", "http://(www\\.)?freeporn\\.to/movie/\\d+", "http://[\\w\\.]*?filebrella\\.com/download/[a-z0-9]+", "https?://(?:www\\.)?(?:storedrives|upshared)\\.com/[A-Za-z0-9]+", "https?://(www\\.)?uploadblast\\.com/[a-z0-9]{12}", "https?://(www\\.)?skyvids\\.net/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?4uploaded\\.com/[A-Za-z0-9]+", "https?://(www\\.)?up4\\.im/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?v-vids\\.com/(vidembed-)?[a-z0-9]{12}", "http://(s\\d000\\.animepremium\\.tv/download/\\d+|embeds\\.animepremium\\.tv/share\\.php\\?id=\\d+)", "https?://(?:www\\.)?(?:putlocker|firedrive)\\.com/.+",
                "http://(www\\.)?sockshare.com/(mobile/)?(file|embed)/[A-Z0-9]+", "https?://(www\\.)?bearfiles\\.in/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?mooshare\\.biz/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?animecloud\\.me/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?aimini\\.net/view/\\?fid=[A-Za-z0-9]+", "https?://(www\\.)?rainy\\.la/(?:embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?project\\-free\\-upload\\.com/.+", "http://(?:www\\.)?(?:netload|netfolder)\\.(?:in|me)/.+", "http://(www\\.)?riotshare\\.com/play/\\d+/", "https?://(www\\.)?premiuns\\.org/[a-z0-9]{12}", "http://[\\w\\.]*?sendfaile\\.com/download/.*?\\.html", "^http://(?:www\\.)?pururin\\.com/(?:view/\\d+/\\d+/[\\-a-z0-9]+_\\d+\\.html|download/\\d+/.+)$", "https?://(www\\.)?tumi\\.tv/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?180upload\\.(com|nl)/((vid)?embed-)?[a-z0-9]{12}",
                "http://(www\\.)?tuspics\\.net/[a-z0-9]{12}", "https?://(www\\.)?stageflv\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?shr77\\.com/[A-Za-z0-9]+", "https?://(www\\.)?filebulk\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?speedy\\-share\\.com/[\\w]+/(.*)", "http://(www\\.)?sloozie\\.com/(galleries/[a-z0-9]+|videos/[a-z0-9]+/.{1})", "http://(www\\.)?otr\\-download\\.de/(download\\.php)?\\?file=[^<>\"\\']+\\.otrkey", "http://(((?!www).*)\\.)?fizy\\.com/?(#?(s|p|u)/(s/)?\\w+)?", "http://(www\\.)?d\\.1tpan\\.com/tp\\d+", "https?://(www\\.)?4uploading\\.com/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?dropvideo\\.com/(embed|video)/[A-Za-z0-9]+", "http://(?:[\\w\\.]*\\.)?(filebox|fbx)\\.ro/((download|down)\\.php\\?k=[0-9a-z]{16}|video/play_video\\.php\\?k=)|http://(?:[\\w\\.]*\\.)?fbx\\.ro/(?:v/)?[0-9a-z]{16}", "https?://(?:www\\.)?vidbux\\.com/.+",
                "https?://(www\\.)?filerock\\.net/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?movreel\\.com/[a-z0-9]{12}", "http://(www\\.)?megavideoz\\.eu/video/[A-Z0-9]+/", "https?://(www\\.)?realvid\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?(?:www\\.)?blip\\.tv/.+", "http://(www\\.)?gulfup\\.com/\\?[A-Za-z0-9]+", "http://(?:www\\.)?hardwareclips\\.com/video/\\d+", "https?://(?:www\\.)?uploadnet\\.co/(?:embed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?files\\.(gw|gameworld)\\.kz/[a-z0-9]+\\.html", "http://(?:www\\.)?files123\\.net/.+", "https?://(?:www\\.)?free4share\\.de/.+", "http://[\\w\\.]*?gettyfile\\.ru/\\d+", "http://[\\w\\.]*?free-share\\.ru/[0-9]+/[0-9]+/", "https?://(www\\.)?rziz\\.net/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?zinwa\\.com/[a-z0-9]{12}", "https?://(?:www\\.)?wuala\\.com/.+", "http://(www\\.)?fileband\\.com/[a-z0-9]{12}",
                "https?://(?:www\\.)?megairon\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?xfileload\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(?:www\\.)?free\\-uploading\\.com/[a-z0-9]{12}", "https?://(www\\.)?fileown\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?verzend\\.be/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?(fileparadox\\.(in|com)|rapidsonic\\.com)/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?filepack\\.pl/[A-Za-z0-9]+", "https?://(www\\.)?goldbytez\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "http://(www\\.)?filemaze\\.ws/.+", "http://(?:www\\.)?(?:divxden|vidxden)\\.(com|to)/(?:embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?vidplay\\.net/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?royalvids\\.eu/(tt/)?[a-z0-9]{12}", "http://(www\\.)?superromworld\\.de/[a-z0-9]+/roms/\\d+/[^<>\"/]+/",
                "http://(www\\.)?n\\-roms\\.de/[a-z0-9]+/index\\.php\\?action=details\\&id=\\d+", "https?://(www\\.)?simpleshare\\.org/[a-z0-9]{12}", "http://(www\\.)?sharebeast\\.com/(mp3embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?sanshare\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?faststream\\.in/[a-z0-9]{12}", "https?://(www\\.)?storedeasy\\.com/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?(jumbofiles\\.org|jumbofilebox\\.com|putcker\\.com|mediafile\\.co|10shared\\.com)/.+", "https?://(www\\.)?uploadlux\\.com/.+", "https?://(www\\.)?linestorage\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?thefile\\.me/[A-Za-z0-9]+", "https?://(www\\.)?muchshare\\.net/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?queenshare\\.com/[A-Za-z0-9]+", "http://(?:www\\.)?videobam\\.com/.+", "https?://(?:www\\.)?mp3the\\.net/[a-z0-9]{12}",
                "https?://(www\\.)?fileforever\\.net/(embed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?quickshare\\.cz/stahnout-soubor/\\d+:[^\\s]+", "https?://(www\\.)?privatehomeclips\\.com/.+", "https?://(www\\.)?warped\\.co/[A-Za-z0-9]+", "https?://(www\\.)?played\\.to/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?topupload1\\.com/[A-Za-z0-9]+", "https?://(www\\.)?creafile\\.net/(vidembed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?creafile\\.com/download/[a-z0-9]+", "https?://(www\\.)?krotix\\.net/[A-Za-z0-9]+", "https?://(www\\.)?akafile\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?videonan\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?uploadbits\\.net/[A-Za-z0-9]+", "http://[\\w\\.]*?upload-drive\\.com/file/\\d+/", "http://(www\\.)?share\\.time\\.mn/download\\.shtml\\?id=[a-z0-9]+", "https?://(www\\.)?pushfile\\.com/[A-Za-z0-9]+",
                "https?://(www\\.)?(uptobox\\.im|fileriio\\.com)/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?dropfiles\\.info/(en/)?download\\.php\\?id=[A-Z0-9]+", "https?://(www\\.)?2drive\\.net/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?400disk\\.com/(file|rf)view_\\d+\\.html", "http://(www\\.)?up\\-loading\\.net/[A-Za-z0-9]+",
                /** turbobit alias' */
                "http://(?:www\\.|new\\.|m\\.)?(filez\\.ninja|savebit\\.net|dz-files\\.ru|file\\.grad\\.by|filesmail\\.ru|gdefile\\.ru|freefo\\.ru|turbovit\\.com\\.ua|share\\.uz|upload\\.uz|files\\.wzor\\.ws|alfa-files\\.com|turbobax\\.net|files\\.prime-speed\\.ru|filestore\\.net\\.ru|file\\.alexforum\\.ws|files\\.best-trainings\\.org\\.ua|bluetooths\\.pp\\.ru|vipgfx\\.net|sharephile\\.com|unextfiles\\.com|filebit\\.org|zharabit\\.net|turbobit\\.name|turboblt\\.ru|maxisoc\\.ru|turbobit\\.pl|turbo-bit\\.ru|file\\.krut-warez\\.ru|vipbit\\.ru|e-flash\\.com\\.ua|upload\\.dwmedia\\.ru|trium-club\\.ru|download\\.uzhgorod\\.name|bayrakweb\\.com|fo\\.letitbook\\.ru|speed-file\\.ru|letitshare\\.ru|files\\.uz-translations\\.uz)/([A-Za-z0-9]+(/[^<>\"/]*?)?\\.html|download/free/[a-z0-9]+|/?download/redirect/[A-Za-z0-9]+/[a-z0-9]+)", "https?://(www\\.)?mxua\\.com/(vidembed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?katzfiles\\.com/[a-z0-9]{12}", "https?://(www\\.)?fsakura\\.com/[a-z0-9]{12}", "https?://(www\\.)?uploadur\\.com/files/\\w+\\.html", "http://[\\w\\.]*?wyslijplik\\.pl/download\\.php\\?sid=\\w{8}", "https?://(www\\.)?tishare\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?share50\\.com/((\\?d|download\\.php\\?id)=[A-Z0-9]+|(en|ru|fr|es)/file/[0-9]+/)", "https?://(www\\.)?med1fire\\.(com|net)/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?dumpfiles\\.org/((vid)?embed\\-)?[a-z0-9]{12}", "http://(www\\.)?videolog\\.tv/video(\\?|\\.php\\?id=)\\d+", "http://[\\w\\.]*?storeplace\\.(org|to)/\\?d=[A-Z0-9]+", "https?://(www\\.)?mojoload\\.com/[a-z0-9]{12}", "http://(www\\.)?ifilehosting\\.net/download\\.php\\?id=[A-Z0-9]+", "https?://(www\\.)?gigfiles\\.net/[a-z0-9]{12}", "https?://(www\\.)?maxisonic\\.com/[A-Za-z0-9]+",
                "https?://(www\\.)?sv-esload\\.com/[A-Za-z0-9]+", "https?://(www\\.)?upgaf\\.com/[A-Za-z0-9]+", "https?://(www\\.)?gulfdown\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?imageeer\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(?:www\\.)?loombo\\.com/[a-z0-9]{12}", "http://(www\\.)?upbrasil\\.info/[a-z0-9]{12}", "https?://(www\\.)?filegig\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?xtraupload\\.net/[A-Za-z0-9]+", "https?://(www\\.)?upservmedia\\.com/[A-Za-z0-9]+", "https?://(www\\.)?cloudlync\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?(ultramegabit\\.com|uploadto\\.us)/file/details/[A-Za-z0-9\\-_]+", "https?://(www\\.)?loudupload\\.(com|net)/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?minoshare\\.com/file/.*?\\.html", "http://(www\\.)?fun\\-vids\\.org/(hosted/media/.*?,\\d+\\.php|((out\\-sticky\\-id\\d+|out\\-id\\d+)[a-z0-9\\-]+\\.html))",
                "http://[\\w\\.]*?flowload\\.com/\\?key=[a-z0-9]+", "http://(www\\.)?divxplanet\\.com/sub/s/\\d+/[A-Za-z0-9\\-_]+\\.html", "https?://(www\\.)?saryshare\\.com/[a-z0-9]{12}", "https?://(www\\.)?uploadrive\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?noelshare\\.com/files/get/[A-Za-z0-9]+", "https://(www\\.)?s\\.yunio\\.com/[A-Za-z0-9]+", "https?://(www\\.)?daj\\.to/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?(?:fileinz|voowl)\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?filerio\\.im/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?boosterking\\.com/[a-z0-9]{12}", "http://(www\\.)?u-tube\\.ru/pages/video/\\d+/", "https?://(www\\.)?medifire\\.net/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?galaxy-file\\.com/[a-z0-9]{12}", "https?://(www\\.)?uploadhunt\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?upload-il\\.com/.+",
                "http://(www\\.)?uploadhero\\.com?/(dl|v)/[A-Za-z0-9]+", "http://(?:www\\.)?filefeltolto\\.hu/(letoltes/[a-z0-9]+/[^<>\"/]+|x/[a-z0-9]+|xvidplayer_gateway\\.php\\?fid=\\d+)", "http://www[\\d]?\\.przeslij\\.net/download\\.php\\?file=(.*)", "http://(www\\.)?altervideo\\.net/.+", "https?://(www\\.)?fileswap\\.com/dl/[A-Za-z0-9]+/", "https?://(www\\.)?safesharing\\.eu/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?japlode\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?shared\\.com/[a-z0-9]+", "https?://(www\\.)?streamit\\.to/[A-Za-z0-9]+", "https?://(www\\.)?ilook\\.to/[A-Za-z0-9]+", "https?://(www\\.)?imgah\\.com/[a-z0-9]{12}", "http://((listen|retro|html5)\\.)?grooveshark\\.com/([#!/%21]+)?((album|artist|playlist|s|user)/.*?/([a-zA-z0-9]+|\\d+)(/music/favorites|/similar)?|popular)|http://[\\w\\-]+\\.grooveshark\\.com/stream\\.php\\?streamKey=\\w+",
                "http://(www\\.)?mais\\.me/download/[A-Z0-9]+", "https?://(www\\.)?megaul\\.com/[a-z0-9]{12}", "http://(www\\.)?maxshare\\.pl/download\\.php\\?dl=[a-z0-9]+", "https?://(www\\.)?mcupload\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?mediavalise\\.com/file/[a-z0-9]+/.*?\\.html", "https?://(www\\.)?uncapped\\-downloads\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?deerfile\\.com/[a-z0-9]{12}", "http://(www\\.)?fupload\\.net/[a-z0-9]{12}", "http://(www\\.)?zomgupload\\.com/.+", "http://(www\\.)?disk\\.84dm\\.com/viewfile\\.php\\?file_id=\\d+", "http://(www\\.)?gfssex\\.com/videos/\\d+/.*?\\.html", "http://(www\\.)?7thsky\\.es/[A-Za-z0-9]+", "http://(www\\.)?2download\\.de/download\\-[a-z0-9]+\\.php", "https?://(www\\.)?filezup\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?fastupload\\.org/(vidembed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?files2share\\.ch/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?metfiles\\.com/download/[a-z0-9]{32}", "http://(www\\.)?(?:1024disk|32666)\\.com/.+", "http://(www\\.)?boojour\\.eu/\\?v=[A-Z0-9]+", "http://(www\\.)?clips\\-and\\-pics\\.org/.+", "http://(www\\.)?axifile\\.com/.+", "https?://(www\\.)?filedust\\.net/(embed\\-)?[a-z0-9]{12}", "https?://((www|audio|doc|file|image|video)\\.)?mixturecloud\\.com/(media/(download/)?|download=)[A-Za-z0-9]+", "https?://(www\\.)?1st\\-files\\.com/[a-z0-9]{12}", "http://(www\\.)?gigabyteupload\\.com/(download\\-|download\\.(html|php)\\?video=)[a-z0-9]{32}", "https?://(www\\.)?filespeed\\.net/(embed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?midupload\\.com/[0-9a-z]{12}", "https?://(www\\.)?rainupload\\.(com|net)/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?kingshare\\.to/[a-z0-9]{12}",
                "http://(www\\.)?mejuba\\.com/(albums/[a-z0-9_\\-]+/\\d+/\\d+/\\d+|embed/(\\d+/\\d+[a-z0-9_\\-]+))", "https?://(www\\.)?xlocker\\.net/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?xvideohost\\.com/video\\.php\\?id=[a-z0-9]+", "https?://[\\w\\.]*?rapidshare\\.(?:com|de)/.+", "http://(www\\.)?dwnshare\\.pl/.+", "https?://(www\\.)?azerfile\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?(lalata|sindema)\\.info/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?seenupload\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?sangfile\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?fileloads\\.cc/(embed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?wdivx\\.com/(play|gateway)/[A-Za-z0-9=]+", "http://(www\\.)?hotsvideos\\.com/video/\\d+", "https?://(www\\.)?lovevideo\\.tv/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?transitfiles\\.com/dl/[A-Za-z0-9]+",
                "https?://(www\\.)?xuploading\\.net/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?asfile\\.com/file/[A-Za-z0-9]+", "https?://(www\\.)?roottail\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?filehostup\\.com/[A-Za-z0-9]+", "https?://(www\\.)?freehostina\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?porntubevidz\\.com/videos/\\d+/[a-z0-9\\-_]+/", "https?://(www\\.)?upchi\\.co\\.il/[a-z0-9]{12}", "https?://(www\\.)?fastvideo\\.eu/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?hostingbulk\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?therapide\\.(com|cz)/(file|download)/[a-z0-9]+", "https?://(www\\.)?yonzy\\.com/.+", "https?://(www\\.)?ravishare\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?vozupload\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?(letitbit\\.tv|getzilla\\.net)/.+", "https?://(www\\.)?videodd\\.net/((vid)?embed-)?[a-z0-9]{12}",
                "https?://(www\\.)?dogefile\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?(nakido\\.com/[A-Z0-9]+|naki\\.do/[a-zA-Z0-9]+)", "https?://(www\\.)?filevice\\.com/[a-z0-9]{12}", "https?://(www\\.)?diskfiles\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?://((www|new|old)\\.)?billionuploads\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?filebite\\.cc/[a-z0-9]{12}", "https?://(www\\.)?gsinfinite\\.com/[A-Za-z0-9]+", "http://(www\\.)?heaven666\\.org/[a-z0-9\\-]+\\-\\d+\\.php", "http://(www\\.)?saganfiles\\.com/download\\.php\\?id=[A-Z0-9]+", "http://(www\\.)?theamateurzone\\.info/(video/|player/config\\.php\\?vkey=|media/player/config_embed\\.php\\?vkey=)\\d+", "https?://(www\\.)?ultrafile\\.me/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?fileb\\.ag/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?k\\-files\\.kz/[a-z0-9]{12}",
                "https?://(www\\.)?clicktoview\\.org/[a-z0-9]{12}", "https?://(www\\.)?(xvidstream\\.net|vidstream\\.in)/[a-z0-9]{12}", "https?://(www\\.)?filemup\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?miloshare\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?lomafile\\.com/.+", "https?://(?:www\\.)?(megacrypter\\.com|encrypterme\\.ga)/(!|%21)[A-Za-z0-9\\-_\\!\\%]+", "https?://(www\\.)?iiiup\\.com/[A-Za-z0-9]+", "http://(www\\.)?digzip\\.com/files/[0-9A-Z]{8}/.{1}", "https?://(www\\.)?senseless\\.tv/[a-z0-9]{12}", "https?://(www\\.)?henchfile\\.com/[a-z0-9]{12}", "https?://(www\\.)?cometfiles\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?mijnbestand\\.nl/(B|b)estand\\-[A-Z0-9]+", "https?://(www\\.)?upafile\\.com/[a-z0-9]{12}", "https?://(www\\.)?bl\\.st/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?filthyrx\\.com/videos/\\d+/[a-z0-9\\-]+\\.html",
                "https?://(www\\.)?turbovid\\.net/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?privatefiles\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?vacishare\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?xerver\\.co/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?qshare\\.com/.+", "https?://(www\\.)?tuxfile\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?gigaup\\.fr/(\\?(d|g)=[A-Z0-9]+|get_file/[A-Z0-9]+/.+\\.html)", "https?://(www\\.)?hddspace\\.com/[a-z0-9]{12}", "https?://(www\\.)?foxishare\\.com/[a-z0-9]{12}", "http://(www\\.)?filestube\\.(com|to)/.+", "http://(www\\.)?(beta\\.)?miloyski\\.com/video\\.html\\?i=[a-z0-9]+", "http://(www\\.)?hidemyass\\.com/files/[A-Za-z0-9]+", "http://(www\\.)?divxhosting\\.net/watch\\-[a-z0-9]+\\.html", "https?://(www\\.)?sube\\.me/((vid)?embed\\-)?[a-z0-9]{12}",
                "http://[\\w\\.]*?quickupload\\.net/([a-z0-9]{12}/uploads/.*?\\.html|[a-z0-9]{12})", "https?://(www\\.)?mydisc\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?isavelink\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?(filestorm\\.to|hulkfile\\.eu|hulkfile\\.com)/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?cruzload\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?bubblefiles\\.com/download\\.php\\?id=[A-Z0-9]+", "https?://(www\\.)?dodane\\.pl/.+", "https?://(www\\.)?bayfiles\\.(com|net)/file/[A-Z0-9]+/[A-Za-z0-9]+/.+", "http://(www\\.)?myuplbox\\.com/file/download/\\d+", "https?://(?:www\\.)?updown\\.bz/[a-zA-Z0-9]+", "https?://(www\\.)?thefilebay\\.com/[a-z0-9]+", "https?://(www\\.)?mukupload\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?box4up\\.com/[A-Za-z0-9]+", "http://(www\\.)?5ilthy\\.com/.+",
                "https?://(www\\.)?filepom\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?dizzcloud\\.com/dl/[a-z0-9]+", "https?://(www\\.)?cloudfly\\.us/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?vidhog\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?slingfile\\.com/((file|audio|video)/.+|dl/[a-z0-9]+/.*?\\.html)", "https?://(www\\.)?iperupload\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://oceanus.ch/u/[0-9a-zA-Z\\-]*/[0-9a-zA-Z\\-]*", "https?://(www\\.)?mrmkv\\-fileshare\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?filejungle\\.com/f/[A-Za-z0-9]+", "http://(www\\.)?fileserve\\.com/file/[a-zA-Z0-9]+", "http://(www\\.)?(zalil|slil)\\.ru/\\d+", "https?://(www\\.)?uploadsat\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?turbotransfer\\.pl/download/[a-z0-9]{32}", "http://(www\\.)?files\\.uploadlab\\.com/(documents|music|videos|photos)/[A-Za-z0-9]+",
                "http://(www\\.)?shareyourfile\\.biz/[a-z0-9]{12}", "http://(www\\.)?tomwans\\.com/(video/[a-z0-9]{32}/|video\\.php\\?v=[a-z0-9]{32})", "http://(www\\.)?(odimusic\\.net|megabox\\.ro)/load/\\?d=[A-Z0-9]+", "http://(www\\.)?failai\\.kava\\.lt/download\\.php\\?id=[A-Z0-9]+", "http://(www\\.)?stahovadlo\\.cz/(soubor/\\d+/[A-Za-z0-9]+|stahnout/\\d+)", "http://((www\\.)?(justin\\.tv)/(?!directory)[^<>/\"]+/((b|c)/\\d+|videos(\\?page=\\d+)?)|(www\\.)?justin\\.tv/archive/archive_popout\\?id=\\d+)", "http://(www\\.)?4share\\.ws/file/[a-z0-9]+/.*?\\.html", "http://[\\w\\.]*?pliczek\\.net/index\\.php\\?p=\\d+", "http://(www\\.)?2gb\\-hosting\\.com/(videos|v)/[a-z0-9]+/.*?\\.html", "https?://(www\\.)?maskfile\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?rockdizfile\\.com/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?(embed\\.)?yesload\\.net/[A-Za-z0-9]+",
                "https?://(www\\.)?dotsemper\\.com/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?mixbird\\.com/mixtapes/(listen|download)/[a-z0-9_\\-]+", "http://(www\\.)?myjizztube\\.com/videos/.*?\\d+\\.html", "http://([a-z]+\\.)?packupload.com/[A-Z0-9]+", "http://(www\\.)*?(en\\.)*?megaszafa\\.com/(plik,(\\d+?)\\.html|[0-9A-Za-z]+/.*)", "https?://(www\\.)?potload\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?usefile\\.com/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?nitrobits\\.com/.+", "http://(www\\.)?uploads\\.center/[A-Za-z0-9]+", "https?://(www\\.)?filemonkey\\.in/file/[a-z0-9]+", "https?://(www\\.)?(mediafilestorage\\.net|multishared\\.me)/((vid)?embed\\-)?[a-z0-9]{12}", "http://(www\\.)?wallbase\\.cc/.+", "https?://(www\\.)?swankshare\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?vidbox\\.yt/((vid)?embed-)?[a-z0-9]{12}",
                "https?://(www\\.)?vidzbeez\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?megafiles\\.se/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?fileom\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?bluehaste\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?socifiles\\.com/d/[0-9a-z]+", "http://[\\w\\.]*?mlfat4arab\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?megashare\\.by/(\\?d|download\\.php\\?id)=[A-Z0-9]+", "http://(www\\.)?flinzy\\.com/d/[A-Za-z0-9]+", "http://(www\\.)?filesend\\.net/download\\.php\\?f=[a-z0-9]+", "http://(www\\.)?fastfileshare\\.com\\.ar/index\\.php\\?p=download\\&hash=[A-Za-z0-9]+", "https?://(www\\.)?(ddlstorage\\.com|ddlsto\\.com)/((vid)?embed\\-)?[a-z0-9]{12}", "http://(www\\.)?spaadyshare\\.com/[A-Za-z0-9]{12}/.+", "https?://(www\\.)?sizfile\\.com/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?hostingcup\\.com/[0-9a-zA-Z]{12}",
                "http://(www\\.)?filecanyon\\.com/file/[a-z0-9]+", "https?://(www\\.)?bytesbox\\.com/(!|%21)/[A-Za-z0-9]+", "https?://(www\\.)?dropvideos\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?tubecloud\\.net/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?xrabbit\\.com/(watch/\\d+/|video/embed/[A-Za-z0-9=]+)", "http://(www\\.)?tubeq\\.net/video/[A-Z0-9]+", "http://(www\\.)?multiupload\\.(com|nl)(:\\d+)?/([A-Z0-9]{2}_[A-Z0-9]+|[0-9A-Z]+)", "https?://(www\\.)?pizzaupload\\.com/[a-z0-9]{12}", "https?://(www\\.)?ntupload\\.com/[a-z0-9]{12}", "http://(www\\.)?magnovideo\\.com/\\?(v|d)=[A-Z0-9]+", "http://(www\\.)?files\\.to/get/[0-9]+/[\\w]+", "https?://(www\\.)?moidisk\\.ru/[a-z0-9]{12}", "http://(www\\.)?vidaru\\.com/[a-z0-9\\-_]+/\\d+", "https?://(www\\.)?epicshare\\.net/((vid)?embed\\-)?[a-z0-9]{12}", "http://(www\\.)?filemov\\.net/download\\.php\\?id=[A-Z0-9]+",
                "https?://(www\\.)?hipfile\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?zingload\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?fileove\\.com/[a-z0-9]{12}", "http://(www\\.)?rnbload\\.com/.+", "https?://(www\\.)?filesaur\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?wrzuc\\.to/([a-zA-Z0-9]+(\\.wt|\\.html)|(en/)?linki/[a-zA-Z0-9]+)", "https?://(www\\.)?hyshare\\.com/[a-z0-9]{12}", "https?://(www\\.)?redload\\.net/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?blitzfiles\\.com/[a-z0-9]{12}", "https?://(www\\.)?qkup\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?lajusangat\\.net/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?my\\.filechum\\.com/[A-Za-z0-9]+", "https?://(www\\.)?uploadnetwork\\.eu/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?videoslim\\.net/((vid)?embed-)?[a-z0-9]{12}",
                "https?://(www\\.)?(dogupload\\.com|filesfrog\\.net)/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?(fiberupload\\.(com|net)|bulletupload\\.com)/[a-z0-9]{12}", "https?://(www\\.)?hottera\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?filego\\.org/\\?d=[A-Z0-9]+", "https?://(www\\.)?putme\\.org/[a-z0-9]{12}", "http://[\\w\\.]*?upshare\\.me/files/[A-Za-z0-9]+/.*?\\.html", "https?://(www\\.)?uploadzeal\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?space4file\\.com/[a-z0-9]{12}", "http://(www\\.)*?mangatraders\\.com/(download|view)/file/\\d+", "http://(www\\.)?nzbload\\.com/en/download/[a-z0-9]+(/\\d+)?", "https?://(www\\.)?vreer\\.com/[a-z0-9]{12}", "https?://(www\\.)?safashare\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?shareprofi\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?crisshare\\.com/(vidembed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?lemuploads\\.com/[a-z0-9]{12}", "https?://(www\\.)?pandapla\\.net/[a-z0-9]{12}", "http://(www\\.)?finaload\\.com/[a-z0-9]+", "http://(www\\.)?shurload\\.es/(download|view)\\.php\\?den=[a-z0-9]{32}", "https?://(www\\.)?megaupdown\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?[a-z]{1,4}[0-9]{1,2}\\.imagehaven\\.net/img\\.php\\?id=[^<>\"/\\[\\]]+\\.[a-z]+", "https?://(www\\.)?filedap\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?limevideo\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?vids\\.bz/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?wallobit\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?davvas\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?uploadinc\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?filelaser\\.com/file/[A-Za-z0-9]+/[^<>\"/]+", "http://(www\\.)?finaload\\.com/[a-z0-9]+",
                "https?://(www\\.)?hostinoo\\.com/[a-z0-9]{12}", "https?://(www\\.)?sinhro\\.net/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?megashare\\.com/.+", "https?://(www\\.)?(berofile|swatupload)\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?uploadizer\\.net/\\?d=[A-Z0-9]+", "https?://(www\\.)?megarelease\\.org/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?share\\-byte\\.net/[A-Za-z0-9]+", "https?://(www\\.)?rapidstation\\.com/[a-z0-9]{12}", "https?://(www\\.)?filechin\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?fujifile\\.me/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?freeuploads\\.fr/\\?d=[A-Z0-9]+", "https?://(www\\.)?guizmodl\\.net/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?file1\\.info/[A-Za-z0-9]+", "https?://(www\\.)?maximusupload\\.com/[a-z0-9]{12}", "https?://(www\\.)?pandamemo\\.com/[a-z0-9]{12}",
                "https?://(www\\.)?(igetfile\\.com|sumofile\\.me)/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?megacloud\\.com/s/[a-zA-Z0-9]{10,}(/[^/<> ]+)?|http://mc\\.tt/[a-zA-Z0-9]{10,}", "https?://(www\\.)?egofiles\\.com/[A-Za-z0-9]+", "https?://(www\\.)?dupload\\.(org|net)/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?cloudvidz\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?videozed\\.net/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?donevideo\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?migaload\\.com/up/[a-z0-9]{12}", "http://(www\\.)?maxvideo\\.pl/(v|u)/[A-Za-z0-9]+", "http://(www\\.)?tgf\\-services\\.com/.+", "https?://(www\\.)?albafile\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?(cramit\\.in|cramitin\\.(net|eu|us))/.+", "https?://(www\\.)?4savefile\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?batshare\\.com/(vidembed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?oleup\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?rapidstone\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "http://(www\\.)?filecopter.net/files/[A-Za-z0-9]+\\.html", "http://(www\\.)?easyfilesharing\\.info(/en|ru|fr|es|de)?/file/\\d+/", "http://(www\\.)?uploadedhd\\.com/[a-f0-9]{16}", "https?://(www\\.)?ilikefile\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?fileomg\\.com/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?([0-9]+\\.)?file\\.am/\\d+", "http://[\\w\\.]*?navihost\\.us/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "https?://(www\\.)?upfile\\.biz/[a-z0-9]{12}", "https?://(www\\.)?dynaupload\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?freevideo\\.cz/vase\\-videa/.*?\\-\\d+\\.html", "https?://(www\\.)?file\\-speed\\.com/[a-z0-9]{12}", "http://(www\\.)?cloudxeon\\.com/[a-z0-9]+",
                "http://(www\\.)?hdplay\\.org/[A-Za-z0-9]+", "https?://(www\\.)?files2upload\\.net/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?dollyshare\\.com/d/\\?file=[a-z0-9]+", "https?://(www\\.)?filetug\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?mirorii\\.com/.+", "http://(www\\.)?fucktube\\.com/video/[0-9]+/.{1}", "http://(www\\.)?faceporn\\.no/video/[a-z0-9\\-]+", "https?://(www\\.)?bitload\\.it/(vidembed\\-)?[a-z0-9]{12}", "http://[\\w\\.]*?beatplexity\\.com/mix/\\?id=\\d+", "http://(www\\.)?bandbase.dk/[^/<>\"\\']+/Track/\\d+/", "https?://(www\\.)?bananahost\\.it/[a-z0-9]{12}", "http://(www\\.)?gigamax\\.ch/\\?d=[A-Z0-9]+", "http://(www\\.)?goldfile\\.eu/[a-z0-9]{12}", "http://(www\\.)?judgeporn\\.com/videos/[a-z0-9\\-_]+", "https?://(www\\.)?elcorillord\\.org/[a-z0-9]{12}", "https?://(www\\.)?rocketfile\\.net/(vidembed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?maxisharing\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?(duckload\\.co|fireloading\\.com)/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?homesexdaily\\.com/(video/.*?\\.html|flv_player/data/playerConfigEmbed/\\d+\\.xml)", "http://(www\\.)?pornbanana\\.com/video(LP)?\\.aspx\\?(\\&)?id=\\d+", "http://(www\\.)?celebritycunt\\.net/video/\\d+", "https?://(www\\.)?speedvid\\.tv/[a-z0-9]{12}", "https?://(www\\.)?filexb\\.com/[a-z0-9]{12}", "http://(www\\.)?upsharez\\.com/[a-z0-9]+", "http://(www\\.)?universalfilehosting\\.com/dl/[A-Za-z0-9]+", "http://(www\\.)?4vid\\.me/embed\\?.+", "http://(www\\.)?nicosound\\.anyap\\.info/sound/sm\\d+", "https?://(www\\.)?evominds\\.com/[a-z0-9]{12}", "https?://(www\\.)?topvideo\\.cc/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?zenfiles\\.biz/(vidembed\\-)?[a-z0-9]{12}",
                "http://(www\\.)?fryhost\\.com/[a-z0-9]+/?[a-z0-9\\-\\.]+", "https?://(www\\.)?turtleshare.com/download/[a-z0-9]+/", "https?://(www\\.)?uploadjet\\.net/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?devilstorage\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?videofox\\.net/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?(u\\d+\\.extabit\\.com/go/[a-z0-9]{13}|extabit\\.com/file(_[^/]+)?/[a-z0-9]{13}(/[A-Za-z0-9]+/[^<>\"/]*?\\.htm)?)", "https?://(www\\.)?videofrog\\.eu/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?nirafile\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?(ompldr|omploader)\\.org/[A-Za-z0-9]+", "http://(www\\.)?speedload\\.org/(\\d+~f|folder/\\d+|[A-Za-z0-9]{2,12})", "https?://(www\\.)?sharefiles\\.co/[a-z0-9]{12}", "http://(www\\.)?upit\\.in/[a-z0-9]{12}", "http://(www\\.)?dump1\\.com/media/\\d+/",
                "http://(www\\.)?fleon\\.me/[a-z]+\\.php\\?Id=[0-9a-f]+", "http://[\\w\\.]*?limelinx\\.com/(files/)?[0-9a-z]+", "https?://(www\\.)?(flashstream\\.in|sharefiles4u\\.com)/[a-z0-9]{12}", "http://(www\\.)?hotuploading\\.com/index\\.php\\?page=main\\&id=[a-z0-9]+(\\&name=[^<>\"\\&/]+)?", "https?://(www\\.)?filecity\\.net/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?servifile\\.com/(get|files)/[^/]+", "https?://(www\\.)?filegag(plus)?\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "http://(www\\.)?sharerun\\.com/[a-z0-9]{12}", "https?://(www\\.)?heftyfile\\.com/[a-z0-9]{12}", "https?://(www\\.)?uploadorb\\.com/[a-z0-9]{12}", "http://(www\\.)?clipshouse\\.com/[a-z0-9]+", "https?://(www\\.)?edoc\\.com/[a-z0-9]{12}", "http://(www\\.)?download\\.fileswappr\\.com/\\?id=\\d+", "http://(www\\.)?filerace\\.com/[a-z0-9]{12}", "https?://(www\\.)?(cloudzer\\.net|clz\\.to)/.+",
                "http://[\\w\\.]*?netdrive\\.ws/\\d+\\.html", "https?://(www\\.)?file4sharing\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?rapidapk\\.com/[a-z0-9]{12}", "http://(www\\.)?docyoushare\\.com/file/index\\.php\\?f=[A-Za-z0-9]+", "https?://(www\\.)?kongsifile\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?vureel\\.com/(video/\\d+|playwire\\.php\\?vid=\\d+)", "http://(www\\.)?dataport\\.cz/file/(?!search)[\\w\\-]+", "https?://(www\\.)?uploadoz\\.com/[a-z0-9]{12}", "http://(www\\.)?warserver\\.cz/stahnout/\\d+", "http://(www\\.)?1clickshare\\.net(/[a-z]+)?/abv\\-fs/\\d+.+", "https?://(www\\.)?cepzo\\.com/[a-z0-9]{12}", "https?://(www\\.)?fireuploads\\.net/[a-z0-9]{12}", "https?://(www\\.)?megaup1oad\\.net/[a-z0-9]{12}", "http://(www\\.)?megaup\\.me/\\?d=[A-Z0-9]+", "https?://(www\\.)?ezzfile\\.(com|it|co\\.nz)/((vid)?embed\\-)?[a-z0-9]{12}",
                "http://(www\\.)?skylo\\.me/[a-z]{2}\\.php\\?Id=[0-9a-f]+", "https?://(www\\.)?filefolks\\.com/[a-z0-9]{12}", "http://(www\\.)?videoslasher\\.com/video/[A-Z0-9]+", "https?://(www\\.)?filebigz\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?filezy\\.net/((vid)?embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?vidx\\.to/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?uploadstation\\.com/file/[A-Za-z0-9]+", "https?://(www\\.)?wooupload\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?ifile\\.ws/[a-z0-9]{12}", "https?://(www\\.)?filesbb\\.com/[a-z0-9]{12}", "https?://(www\\.)?ihostia\\.com/[a-z0-9]{12}", "https?://(www\\.)?youload\\.me/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?ok2upload\\.com/[a-z0-9]{12}", "https?://(www\\.)?bitupload\\.com/((file/p/id|hosting/download/index/p/id)/[a-z0-9]+|[a-z0-9]{12})",
                "http://[\\w\\.]*?cobrashare\\.sk(/downloadFile\\.php\\?id=.+|:[0-9]+/CobraShare\\-v\\.0\\.9/download/.+id=.+)", "https?://(www\\.)?enjoybox\\.in/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?share4files\\.com/files/[A-Za-z0-9]+\\.html", "https?://(www\\.)?up\\.msrem\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?megaload\\.it/[a-z0-9]{12}", "http://(www\\.)?terafiles\\.net/v-\\d+\\.html", "https?://(www\\.)?freestorage\\.ro/[a-z0-9]{12}", "https?://(www\\.)?filekai\\.com/((vid)?embed-)?[a-z0-9]{12}", "http://(www\\.)?divxforevertr\\.com/index\\.php\\?act=subz\\&CODE=03\\&id=\\d+", "http://[\\w\\.]*?filekeeping\\.de/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "https?://(www\\.)?livefile\\.org/get/[A-Za-z0-9]+", "http://(www\\.)?iranfilm16\\.com/forum/dl\\.php\\?serverid=\\d+\\&file=[^<>\"]+",
                "http://(www\\.)?isharemybitch\\.com/(galleries/\\d+/[a-z0-9\\-]+|videos/\\d+/.*?)\\.html", "http://(www\\.)?shufuni\\.com/(?!Flash/)(VideoLP\\.aspx\\?videoId=\\d+|[\\w\\-\\+]+\\d+|handlers/FLVStreamingv2\\.ashx\\?videoCode=[A-Z0-9\\-]+)", "http://(www\\.)?belgeler\\.com/blg/[a-z0-9]+/", "http://(www\\.)?loadhero\\.net/[A-Za-z0-9]+", "https?://(www\\.)?ngsfile\\.com/[a-z0-9]{12}", "http://(www\\.)?1\\-clickshare\\.com/(\\d+|download2\\.php\\?a=\\d+)", "https?://(www\\.)?fastsonic\\.net/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?brutalsha\\.re/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?moviesnxs\\.com/web/gallery/mnxs\\.php\\?id=\\d+", "https?://(www\\.)?hotfile\\.com/dl/\\d+/[0-9a-zA-Z]+/(.*?/|.+)?", "https?://(www\\.)?sharedbit\\.net/(file/\\d+|[a-z0-9]+)", "https?://(www\\.)?ufox\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?comload\\.net/[a-z0-9]{12}",
                "http://(www\\.)?6ybh-upload\\.com/[a-z0-9]{12}", "https?://(www\\.)?cloudnes\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?fileprohost\\.com/[a-z0-9]{12}", "https?://(www\\.)?cyberlocker\\.ch/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?filebox\\.com/((vid)?embed-)?[a-z0-9]{12}", "https?://(www\\.)?x7files\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?videozer\\.com/(video|embed)/[A-Za-z0-9]+", "https?://(www\\.)?megabitshare\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?filestay\\.com/[a-z0-9]{12}", "https?://(www\\.)?uplly\\.com/[a-z0-9]{12}", "http://(www\\.)?asixfiles\\.com/[a-z0-9]{12}", "https?://(www\\.)?zefile\\.com/[a-z0-9]{12}", "https?://(www\\.)?kingsupload\\.com/[a-z0-9]{12}", "https?://(www\\.)?fileking\\.co/[a-z0-9]{12}", "https?://(www\\.)?sharevid\\.co/((vid)?embed-)?[a-z0-9]{12}",
                "http://(www\\.)?4fastfile\\.com(/[a-z]+)?/abv\\-fs/[\\d\\-]+/.+", "http://(www\\.)?1\\-upload\\.com(/[a-z]+)?/abv\\-fs/\\d+.+", "http://(www\\.)?dump\\.ro/[0-9A-Za-z/\\-\\.\\?\\=\\&]+", "https?://(www\\.)?dippic\\.com/[a-z0-9]{12}", "http://(www\\.)?uploking\\.com/file/[A-Za-z0-9_\\-]+/", "http://(www\\.)?(www\\d+\\.)?zshare(\\.net)?\\.ma/[a-z0-9]{12}", "http://(www\\.)?book\\-mark\\.net/videos/\\d+/.*?\\.html", "https?://(www\\.)?ginbig\\.com/[a-z0-9]{12}", "https?://(www\\.)?ddl\\.mn/[a-z0-9]{12}", "https?://(www\\.)?syfiles\\.com/[a-z0-9]{12}", "https?://(www\\.)?iuploadfiles\\.com/[a-z0-9]{12}", "https?://(www\\.)?thexyz\\.net/[a-z0-9]{12}", "http://(www\\.)?dl\\d+\\.zakachali\\.(net|com)/file/\\d+", "http://(www\\.)?indianpornvid\\.com/[A-Za-z0-9\\-_]+videos\\d+\\.html", "https?://(www\\.)?hotfiles\\.ws/(vidembed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?wizzupload\\.com/[a-z0-9]{12}", "https?://(www\\.)?banashare\\.com/((vid)?embed\\-)?[a-z0-9]{12}", "http://(www\\.)?downupload\\.com/[a-z0-9]{12}", "http://(www\\.)?putshare\\.com/[a-z0-9]{12}", "http://(www\\.)?vidbox\\.net/file\\.php\\?fd=[0-9a-f]+", "http://(www\\.)?filetube\\.to/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(www\\.)?nowveo\\.com/file/\\d+/", "http://(www\\.)?uploadic\\.com/[a-z0-9]{12}", "https?://(www\\.)?flashdrive\\.it/(upload/)?[a-z0-9]{12}", "https?://(www\\.)?flashdrive\\.(uk\\.com|it)(/upload)?/[a-z0-9]{12}", "https?://(www\\.)?filewinds\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?wrzucaj\\.com/\\d+", "http://(www\\.)?yourfilestore\\.com/download/\\d+/[^<>\"]+\\.html", "https?://(www\\.)?toucansharing\\.com/[a-z0-9]{12}", "http://(www\\.)?uploaddot\\.com/[a-z0-9]{12}",
                "https?://(www\\.)?zooupload\\.com/(embed\\-)?[a-z0-9]{12}", "https?://(www\\.)?uploadcore\\.com/[a-z0-9]{12}", "https?://(www\\.)?spaceha\\.com/[a-z0-9]{12}", "http://(www\\.)?tubethumbs\\.com/galleries/\\d+/\\d+/.*?\\.php", "https?://(www\\.)?peeje(share)?\\.com/files/\\d+/[^<>\"\\'/]+", "http://(www\\.)?(datacloud|mediacloud)\\.to/download/[a-z0-9]+/.{1}", "http://(www\\.)?xxxmsncam\\.com/\\d+{4}/\\d+{2}/\\d+{2}/[^<>\"\\'/]+/", "https?://(www\\.)?uploadboxs\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?247upload\\.com/[a-z0-9]{12}", "http://(www\\.)?fileshare\\.in\\.ua/[0-9]+", "http://[\\w\\.]*?upload\\.tc/download/\\d+/.*?\\.html", "http://(www\\.)?filesmall\\.com/[A-Za-z0-9]+/download\\.html", "https?://(www\\.)?fileuplo\\.de/[a-z0-9]{12}", "https?://(www\\.)?quakefile\\.com/((vid)?embed\\-)?[a-z0-9]{12}",
                "https?://(www\\.)?wupfile\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?vdoreel\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?flazhshare\\.com/[a-z0-9]{12}", "https?://(www\\.)?upmorefiles\\.com/[a-z0-9]{12}", "http://(www\\.)?cloudyload\\.com/[A-Za-z0-9]+(~f)?", "http://(www\\.)?icyfiles\\.com/[a-z0-9]+", "https?://(www\\.)?vidpe\\.com/[a-z0-9]{12}", "https?://(www\\.)?clouds\\.to/[a-z0-9]{12}", "https?://(www\\.)?zuzufile\\.com/[a-z0-9]{12}", "http://(www\\.)?hostfil\\.es/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(www\\.)?onlinedisk\\.ru/(file|view)/[0-9]+", "https?://(www\\.)?fileduct\\.com/[a-z0-9]{12}", "http://(www\\.)?frogup\\.com/plik/pokaz/[^<>\"/]*?/[0-9]+", "http://(www\\.)?filejumbo\\.com/Download/[A-Z0-9]+", "http://(www\\.)?dump\\.ru/file/[0-9]+",
                "http://(www\\.)?fileshawk\\.com/files/[A-Za-z0-9]+\\.html", "https?://(www\\.)?vidstream\\.us/[a-z0-9]{12}", "https?://(www\\.)?filezpro\\.com/[a-z0-9]{12}", "http://(www\\.)?fileupper\\.com/[a-z0-9]{12}", "http://(www\\.)?speedy\\-share\\.net/(?!faq|register|login|terms|report_file|plugins)[a-z0-9]+", "http://[\\w\\.]*?files\\.ge/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "https?://(www\\.)?gbitfiles\\.com/[a-z0-9]{12}", "https?://(www\\.)?xtilourbano\\.info/[a-z0-9]{12}", "https?://(www\\.)?allbox4\\.com/(\\-embed)?[a-z0-9]{12}", "https?://(www\\.)?arab\\-box\\.com/[a-z0-9]{12}", "https?://(www\\.)?farmupload\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?filedefend\\.com/[a-z0-9]{12}", "https?://(www\\.)?filesega\\.com/[a-z0-9]{12}", "https?://(www\\.)?kupload\\.org/[a-z0-9]{12}",
                "https?://(www\\.)?multishare\\.org/file/[a-z0-9]{12}/.*?\\.html", "https?://(www\\.)?98file\\.com/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?wantload\\.com/[a-z0-9]{12}", "http://(www\\.)?esnips\\.com/((ns)?doc/[a-z0-9\\-]+|displayimage\\.php\\?[\\w\\&\\=]+)", "https?://(www\\.)?uload\\.to/(vidembed\\-)?[a-z0-9]{12}", "https?://(www\\.)?share76\\.com/[a-z0-9]{12}(/[^<>\"/]+)?", "https?://(www\\.)?filemates\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?stahnu\\.to/files/get/[A-Za-z0-9]+/[A-Za-z0-9_\\-% ]+", "http://(www\\.)?filestock\\.ru/[a-z0-9]{12}", "http://[\\w\\.]*?uploader.pl/([a-z]{2}/)?file/\\d+/", "http://[\\w\\.]*?mach2upload\\.com/files/[A-Za-z0-9]+\\.html", "http://(www\\.)?megaunload\\.net/index\\.php/files/get/[A-Za-z0-9_\\-]+", "http://(www\\.)?app04\\.bonpoo\\.com/cgi\\-bin/download\\?fid=[A-Z0-9]+",
                "http://(www\\.)?modovideo\\.com/video(\\.php)?\\?v=[a-z0-9]+|https?://(www\\.)?modovideo\\.com/[a-z0-9]{12}", "http://(www\\.)?bitoman\\.ru/download/\\d+\\.html", "https?://(www\\.)?maknyos\\.com/[a-z0-9]{12}", "https?://(www\\.)?upgrand\\.com/[a-z0-9]{12}", "https?://(www\\.)?pigsonic\\.com/[a-z0-9]{12}", "https?://(www\\.)?filevelocity\\.com/[a-z0-9]{12}", "https?://(www\\.)?filegaze\\.com/[a-z0-9]{12}", "https?://(www\\.)?ddldrive\\.com/[a-z0-9]{12}", "https?://(www\\.)?fileforth\\.com/[a-z0-9]{12}", "http://(www\\.)?files\\-save\\.com/(fr|en)/download\\-[a-z0-9]{32}\\.html", "http://(www\\.)?media\\-4\\.me/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "https?://(www\\.)?backupload\\.net/[a-z0-9]{12}", "http://(www\\.)?upafacil\\.com/(file/\\d+/|\\?d=)[\\w\\-\\.]+", "https?://(www\\.)?filedownloads\\.org/[a-z0-9]{12}",
                "http://(www\\.)?filesector\\.cc/f/[A-Z0-9]+/", "http://(www\\.)?netuploaded\\.com/[a-z0-9]{12}", "https?://(www\\.)?squillion\\.com/[a-z0-9]{12}", "https?://(www\\.)?sharebees\\.com/(vidembed\\-)?[a-z0-9]{12}", "http://(www\\.)?filetobox\\.com/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(www\\.)?mojedata\\.sk/[A-Za-z0-9_]+", "https?://(www\\.)?grupload\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?stickam\\.com/viewMedia\\.do\\?mId=\\d+", "http://(www\\.)?gimmedatnewjoint\\.com/play/\\d+/", "http://(www\\.)?dup\\.co\\.il/(file\\.php\\?akey=|v/)[\\w]{14}", "http://(www\\.)?eazyupload\\.net/(download/)?[A-Za-z0-9]+", "http://(www\\.)?depoindir\\.com/files/get/[A-Za-z0-9]+", "http://[\\w\\.]*?own3d\\.tv/(.*?/)?(video|watch)/\\d+", "http://(www\\.)?drop\\.st/[A-Za-z0-9]+", "http://(www\\.)?favupload\\.com/(video|file|audio)/\\d+/",
                "http://(www\\.)?anonstream\\.com/get_[A-Za-z0-9]+", "https?://(www\\.)?odsiebie\\.pl/[a-z0-9]{12}", "https?://(www\\.)?shareupload\\.com/[a-z0-9]{12}", "http://(www\\.)?filebeer\\.info/(\\d+~f|[A-Za-z0-9]+)", "http://[\\w\\.]*?uploadfloor\\.com/[a-z0-9]{12}", "https?://(www\\.)?venusfile\\.com/[a-z0-9]{12}", "https?://(www\\.)?welload\\.com/[a-z0-9]{12}", "https?://(www\\.)?upaj\\.pl/[a-z0-9]{12}", "http://(www\\.)?shareupload\\.net/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es|de)/)?file/[0-9]+/)", "https?://(www\\.)?tsarfile\\.com/[a-z0-9]{12}", "http://(www\\.)?omegave\\.org/[a-z0-9]{12}", "http://((www\\.)?(fsx|mfs\\.hu/download\\.php\\?s=\\d+\\&d=[^<>\"]+\\&h=[a-z0-9]+|s.*?\\.(fsx|mfs)\\.hu/.+/.+))", "http://(www\\.)?kiwiload\\.com/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es|de)/)?file/[0-9]+/)", "https?://(www\\.)?gbmeister\\.com/[a-z0-9]{12}",
                "http://(www\\.)?filesharing88\\.net/public/(?!(faq|register|login|terms|report_file|aboutus|contact|forgot|help|inthenews|privacy|upgrade)\\.html)[a-z0-9]+(?!~|%7Ef)", "https?://(www\\.)?fileza\\.net/[a-z0-9]{12}", "https?://(www\\.)?filecloud\\.ws/[a-z0-9]{12}", "https?://(www\\.)?filesome\\.com/[a-z0-9]{12}", "https?://(www\\.)?filehost\\.ws/[a-z0-9]{12}", "https?://(www\\.)?filemade\\.com?/[a-z0-9]{12}", "https?://(www\\.)?bloonga\\.com/[a-z0-9]{12}", "http://(www\\.)?zettaupload\\.com/(?!file_category|latest_file|wklej|terms|report_file|partners|contact|faq|login|register)[a-z0-9]+", "https?://(www\\.)?(aa\\.vg|aavg\\.net)/[a-z0-9]{12}", "http://(www\\.)?freeporn\\.com/(video/\\d+/|[a-z0-9\\-_]+\\-\\d+)", "http://(www\\.)?bitbonus\\.com/download/[A-Za-z0-9\\-]+", "https?://(www\\.)?sharebeats\\.com/[a-z0-9]{12}", "http://(www\\.)?vidhost\\.me/\\?dw?=[A-Z0-9]+",
                "https?://(www\\.)?filetechnology\\.com/[a-z0-9]{12}", "http://(www\\.)?badongo\\.com/.+", "https?://(www\\.)?uptorch\\.com/\\?d=[A-Z0-9]{9}", "http://(www\\.)?videoveeb\\.(com|net)/\\?dw?=[A-Z0-9]+", "http://(www\\.)?fileupped\\.com/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "https?://(www\\.)?repofile\\.com/[a-z0-9]{12}", "https?://(www\\.)?filemsg\\.com/[a-z0-9]{12}", "https?://(www\\.)?dopeshare\\.com/[a-z0-9]{12}", "https?://(www\\.)?filefat\\.com/[a-z0-9]{12}", "http://(www\\.)?fileplayground\\.com/[a-z0-9]{12}", "https?://(www\\.)?fileor\\.com/[a-z0-9]{12}", "https?://(www\\.)?aieshare\\.com/[a-z0-9]{12}", "http://(www\\.)?q4share\\.com/[a-z0-9]{12}", "http://(www\\.)??share\\-now\\.net/{1,}files/\\d+\\-.*?\\.html", "https?://(www\\.)?1hostclick\\.com/[a-z0-9]{12}", "https?://(www\\.)?mummyfile\\.com/[a-z0-9]{12}",
                "http://(www\\.)?hsupload\\.(com|net)/\\?dw?=[A-Z0-9]+", "https?://(www\\.)?upthe\\.net/[a-z0-9]{12}", "https?://(www\\.)?ufile\\.eu/[a-z0-9]{12}", "http://(www\\.)?(bitroad\\.net|filemashine\\.com|friendlyfiles\\.net|vip4sms\\.com|manuls\\.ru)/download/[A-Fa-f0-9]+", "http://(www\\.)?coolshare\\.cz/stahnout/\\d+", "http://(www\\.)?speedfile\\.cz/((cs|en|de)/)?\\d+/[a-z0-9\\-]+", "https?://(www\\.)?your\\-filehosting\\.com/[a-z0-9]{12}", "http://(www\\.)?brontofile\\.com/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "https?://(www\\.)?filestrum\\.com/[a-z0-9]{12}", "https?://(www\\.)?filedove\\.com/[a-z0-9]{12}", "https?://(www\\.)?sharpfile\\.com/(?!folder/|banners|contact|images|register|privacy|premium|affiliates|language|resellers)[a-z0-9]{6,12}", "https?://(www\\.)?filerose\\.com/[a-z0-9]{12}",
                "https?://(www\\.)?filereactor\\.com/[a-z0-9]{12}", "https?://(www\\.)?boltsharing\\.com/[a-z0-9]{12}", "http://(www\\.)?turboupload\\.com/[a-z0-9]+", "http://(www\\.)?(uploads\\.glumbo|glumbouploads)\\.com/[a-z0-9]{12}", "https?://(www\\.)?terabit\\.to/[a-z0-9]{12}", "http://(www\\.)?buckshare\\.com/[a-z0-9]{12}", "https?://(www\\.)?zeusupload\\.com/[a-z0-9]{12}", "https?://(www\\.)?filedino\\.com/[a-z0-9]{12}", "http://(www\\.)?(appscene\\.org|filedude\\.com)/(download/[0-9a-zA-Z]+|download\\.php\\?id=\\d+)", "http://(www\\.)?(new\\.)?uptal\\.(com|org)/\\?d=[A-Fa-f0-9]+", "http://(www\\.)?uptal\\.net/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(www\\.)?file-bit\\.net/[a-z0-9]{12}", "http://(www\\.)?xtshare\\.com/toshare\\.php\\?Id=\\d+(\\&view=[0-9a-f]+)?",
                "http://(www\\.)?cosaupload\\.org/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es|de)/)?file/[0-9]+/)", "http://(www\\.)?sharing\\-online\\.com/[a-z0-9]{12}", "http://(www\\.)?filestrack\\.com/[a-z0-9]{12}", "http://(www\\.)?shareator\\.net/[0-9a-z]+", "http://(www\\.)?azushare\\.net/[A-Za-z0-9]+/", "https?://(www\\.)?filecosy\\.com/[a-z0-9]{12}", "https?://(www\\.)?monsteruploads\\.eu/[a-z0-9]{12}(/[^<>\"/]*?)?\\.html", "https?://(www\\.)?vidhuge\\.com/[a-z0-9]{12}", "http://(www\\.)?doneshare\\.com/files/details/[a-z0-9\\-]+\\.html", "http://(www\\.)?cixup\\.com/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "https?://(www\\.)?animegoon\\.com/[a-z0-9]{12}", "http://(www\\.)?supermov\\.com/(rc|video)/[0-9]+", "https?://(www\\.)?ufliq\\.com/[a-z0-9]{12}", "http://(www\\.)?vidreel\\.com/video/[0-9a-zA-Z]+/",
                "http://(www\\.)?deditv\\.com/(play|gate\\-way)\\.php\\?v=[0-9a-f]+", "http://(www\\.)?(hotshare|supershare)\\.net/(.+/)?(file|audio|video)/.+", "https?://(www\\.)?shareshared\\.com/[a-z0-9]{12}", "http://(www\\.)?uploadville\\.com/[a-z0-9]{12}", "http://(www\\.)?fileserver\\.cc/[a-z0-9]{12}", "http://(www\\.)?bebasupload\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?savefile\\.ro/[\\w]+/?", "http://(www\\.)?ovfile\\.com/[a-z0-9]{12}", "https?://(www\\.)?divxbase\\.com/[a-z0-9]{12}", "https?://(www\\.)?gptfile\\.com/[a-z0-9]{12}", "https?://(www\\.)?dudupload\\.com/[a-z0-9]{12}", "http://(www\\.)?eyvx\\.com/[a-z0-9]{12}", "http://(www\\.)?farshare\\.to/[a-z0-9]{12}", "http://(www\\.)?azsharing\\.com/[a-z0-9]{12}/", "http://(www\\.)?freefilessharing\\.com/[a-z0-9]{12}", "https?://(www\\.)?elitedisk\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?freakmov\\.com/(rc|video)/[0-9]+",
                "http://[\\w\\.]*?(shragle|cloudnator)\\.(com|de)/files/[\\w]+/.*", "http://[\\w\\.]*?filesavr\\.com/[A-Za-z0-9]+(_\\d+)?", "http://(www\\.)?saveufile\\.(in\\.th|com)/car\\.php\\?file=[a-z0-9]+", "https?://(www\\.)?migahost\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?fastfreefilehosting\\.com/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "https?://(www\\.)?files2k\\.eu/[a-z0-9]{12}", "https?://(www\\.)?shafiles\\.me/[a-z0-9]{12}", "http://(www\\.)?jalurcepat\\.com/[a-z0-9]{12}", "https?://(www\\.)?(divload|divupload)\\.org/(embed\\-)?[a-z0-9]{12}", "http://(www\\.)?refile\\.net/(d|f)/\\?[\\w]+", "http://[\\w\\.]*?oron\\.com/[a-z0-9]{12}", "http://(www\\.)?wupload\\.[a-z]{1,5}/file/([0-9]+(/.+)?|[a-z0-9]+/[0-9]+(/.+)?)", "http://[\\w\\.]*?(sharingmatrix|filesonic)\\..*?/.*?file/([a-zA-Z0-9]+(/.+)?|[a-z0-9]+/[0-9]+(/.+)?|[0-9]+(/.+)?)",
                "https?://(www\\.)?xxlupload\\.com/[a-z0-9]{12}", "http://(www\\.)?cumfox\\.com/videos/.*?-\\d+\\.html", "http://(www\\.)?pyramidfiles\\.com/[a-z0-9]{12}", "http://(www\\.)?nahraj\\.cz/content/(view|download)/[a-z0-9]+\\-[a-z0-9]+\\-[a-z0-9]+\\-[a-z0-9]+\\-[a-z0-9]+", "http://(www\\.)?jsharer\\.com/download/[a-z0-9]+\\.htm", "https?://(www\\.)?annonhost\\.net/[a-z0-9]{12}", "http://(www\\.)?filekeeper\\.org/download/[0-9a-zA-Z]+/([\\(\\)0-9A-Za-z\\.\\-_% ]+|[/]+/[\\(\\)0-9A-Za-z\\.\\-_% ])", "http://(www\\.)?dynyoo\\.com/\\?goto=dl\\&id=[a-z0-9]{32}", "http://[\\w\\.]*?163pan\\.com/files/[a-z0-9]+\\.html", "http://[\\w\\.]*?imagehost\\.org/(download/[0-9]+/.+|[0-9]+/.+)", "http://[\\w\\.]*?4us\\.to/download\\.php\\?id=[A-Z0-9]+", "http://[\\w\\.]*?yabadaba\\.ru/files/[0-9]+", "http://(www\\.)?madshare\\.com/(en/)?download/[a-zA-Z0-9]+/",
                "http://(www\\.)?diglo\\.com/download/[a-z0-9]+", "http://(www\\.)?tubeload\\.to/file(\\d+)?\\-.+", "http://(www\\.)?tunabox\\.net/files/[A-Za-z0-9]+\\.html", "http://[\\w\\.]*?yourfilehost\\.com/media\\.php\\?cat=.*?\\&file=.+", "https?://(www\\.)?uploadegg\\.com/[a-z0-9]{12}", "http://(www\\.)?brsbox\\.com/filebox/down/fc/[a-z0-9]{32}", "http://(www\\.)?amateurboobtube\\.com/videos/\\d+/.*?\\.html", "http://(www\\.)?good\\.net/.+", "http://(www\\.)*?(freeload|mcload)\\.to/(divx\\.php\\?file_id=|\\?Mod=Divx\\&Hash=)[a-z0-9]+", "http://(www\\.)?netporn\\.nl/watch/[a-z0-9]+/.{1}", "http://(www\\.)?przeklej\\.pl/(d/\\w+/|\\d+|plik/)[^\\s]+", "http://(www\\.)?alldrives\\.ge/main/linkform\\.php\\?f=[a-z0-9]+", "http://(www\\.)?allshares\\.ge/(\\?d|download\\.php\\?id)=[A-Z0-9]+", "https?://(www\\.)?holderfile\\.com/[a-z0-9]{12}",
                "http://(www\\.)?megashare\\.vnn\\.vn/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(www\\.)?link\\.ge/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(www\\.)?up\\.jeje\\.ge//((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(www\\.)?up\\-4\\.com/(\\?d|download\\.php\\?id)=[A-Z0-9]+", "https?://(www\\.)?cloudcache\\.cc/[a-z0-9]{12}", "https?://(www\\.)?(ddlanime\\.com|ddlani\\.me)/[a-z0-9]{12}", "http://(www\\.)?mountfile\\.com/file/[a-z0-9]+/[a-z0-9]+", "http://(www\\.)?platinshare\\.com/files/[A-Za-z0-9]+", "http://(www\\.)?megavideo\\.com/(.*?(v|d)=|v/)[a-zA-Z0-9]+", "http://(www\\.)?megaupload\\.com/.*?(\\?|&)d=[0-9A-Za-z]+", "http://(www\\.)?(megaporn|megarotic|sexuploader)\\.com/(.*?v=|v/)[a-zA-Z0-9]+", "http://(www\\.)?zshare\\.net/.+",
                "http://(www\\.)?uploading4u\\.com/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(www\\.)?megafree\\.kz/file\\d+", "http://(www\\.)?batubia\\.com/[a-z0-9]{12}", "http://(www\\.)?upload24\\.net/[a-z0-9]+\\.[a-z0-9]+", "http://(www\\.)?download\\.files\\.namba\\.kz/files/\\d+", "http://(www\\.)?datumbit\\.com/file/.*?/", "http://(www\\.)?fik1\\.com/[a-z0-9]{12}", "http://(www\\.)?fileape\\.com/(index\\.php\\?act=download\\&id=|dl/)\\w+", "http://(www\\.)?filezzz\\.com/download/[0-9]+/", "http://(www\\.)?imagewaste\\.com/pictures/\\d+/.{1}", "http://(www\\.)?fyels\\.com/[A-Za-z0-9]+", "http://(www\\.)?gotupload\\.com/[a-z0-9]{12}", "http://(go.sharehub.com|sharehub.me|follow.to|kgt.com|krt.com)/.*", "http://(www\\.)?sharehut\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?(filesurf|4ppl|files\\.youmama)\\.ru/[0-9]+",
                "http://[\\w\\.]*?openfile\\.ru/[0-9]+", "http://[\\w\\.]*?letitfile\\.(ru|com)/download/id\\d+", "http://[\\w\\.]*?tab\\.net\\.ua/sites/files/site_name\\..*?/id\\.\\d+/", "http://[\\w\\.]*?uploadbox\\.com/.*?files/[0-9a-zA-Z]+", "http://(www\\.)?supashare\\.net/[a-z0-9]{12}", "https?://(www\\.)?usershare\\.net/[a-z0-9]{12}", "http://(www\\.)?skipfile\\.com/[a-z0-9]{12}", "http://(www\\.)?10upload\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?x7\\.to/(?!list)[a-zA-Z0-9]+(/(?!inList)[^/\r\n]+)?", "http://(www\\.)?uploadking\\.com/[A-Z0-9]+", "http://(www\\.)?uploadhere\\.com/[A-Z0-9]+", "http://[\\w\\.]*?fileshaker\\.com/.+", "http://(www\\.)?vistaupload\\.com/[a-z0-9]{12}", "https?://(www\\.)?groovefile\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?enterupload\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?xshareware\\.com/[\\w]+/.*", "http://[\\w\\.]*?xun6\\.(com|net)/file/[a-z0-9]+",
                "http://(www\\.)?yourupload\\.de/[a-z0-9]{12}", "http://(www\\.)?youshare\\.eu/[a-z0-9]{12}", "http://(www\\.)?mafiaupload\\.com/do\\.php\\?id=\\d+", "http://[\\w\\.]*?addat.hu/.+/.+", "http://(www\\.)?archiv\\.to/((\\?Module\\=Details\\&HashID\\=|GET/)FILE[A-Z0-9]+|view/divx/[a-z0-9]+)", "http://[\\w\\.]*?bigupload\\.com/(d=|files/)[A-Z0-9]+", "http://(www\\.)?biggerupload\\.com/[a-z0-9]{12}", "http://(www\\.)?(bitload\\.com/(f|d)/\\d+/[a-z0-9]+|mystream\\.to/file-\\d+-[a-z0-9]+)", "https?://(www\\.)?bufiles\\.com/[a-z0-9]{12}", "http://(www\\.)?cash-file\\.(com|net)/[a-z0-9]{12}", "http://[\\w\\.]*?combozip\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?(duckload\\.com|youload\\.to)/(download/[a-z0-9]+|(divx|play)/[A-Z0-9\\.-]+|[a-zA-Z0-9\\.]+)", "http://(www\\.)?exoshare\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?file2upload\\.(net|com)/download/[0-9]+/",
                "http://[\\w\\.]*?filebase\\.to/(files|download)/\\d{1,}/.*", "http://[\\w\\.]*?filebling\\.com/[a-z0-9]{12}", "http://(www\\.)?filecrown\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?filefrog\\.to/download/\\d+/[a-zA-Z0-9]+", "http://[\\w\\.]*?filefront\\.com/[0-9]+", "http://(www\\.)?filehook\\.com/[a-z0-9]{12}", "http://(www\\.)?filestage\\.to/watch/[a-z0-9]+/", "http://(www\\.)?(filezup|divxupfile)\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?fullshare\\.net/show/[a-z0-9]+/.+", "http://(www\\.)?gaiafile\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?keepfile\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?kewlshare\\.com/dl/[\\w]+/", "http://[\\w\\.]*?lizshare\\.net/[a-z0-9]{12}", "http://(www\\.)?loaded\\.it/(show/[a-z0-9]+/[A-Za-z0-9_\\-% \\.]+|(flash|divx)/[a-z0-9]+/)", "http://[\\w\\.]*?loadfiles\\.in/[a-z0-9]{12}",
                "(http://[\\w\\.]*?megarapid\\.eu/files/\\d+/.+)|(http://[\\w\\.]*?megarapid\\.eu/\\?e=403\\&m=captcha\\&file=\\d+/.+)", "http://[\\w\\.]*?(megashare\\.vn/(download\\.php\\?uid=[0-9]+\\&id=[0-9]+|dl\\.php/\\d+)|share\\.megaplus\\.vn/dl\\.php/\\d+)", "http://(www\\.)?metahyper\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?missupload\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?netstorer\\.com/[a-zA-Z0-9]+/.+", "http://[\\w\\.]*?nextgenvidz\\.com/view/\\d+", "http://(www\\.)?piggyshare\\.com/file/[a-z0-9]+", "http://(www\\.)?profitupload\\.com/files/[A-Za-z0-9]+\\.html", "http://[\\w\\.]*?quickload\\.to/\\?Go=Player\\&HashID=FILE[A-Z0-9]+", "http://[\\w\\.]*?quickyshare\\.com/[a-z0-9]{12}", "http://[\\w\\.]*?share\\.cx/(files/)?\\d+", "http://[\\w\\.]*?sharehoster\\.(de|com|net)/(dl|wait|vid)/[a-z0-9]+", "http://[\\w\\.]*?shareua.com/get_file/.*?/\\d+",
                "http://[\\w\\.]*?speedload\\.to/FILE[A-Z0-9]+", "http://(www\\.)?upfile\\.in/[a-z0-9]{12}", "http://[\\w\\.]*?ugotfile.com/file/\\d+/.+", "http://[\\w\\.]*?upload\\.ge/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://[\\w\\.]*?uploadmachine\\.com/(download\\.php\\?id=[0-9]+&type=[0-9]{1}|file/[0-9]+/)", "http://[\\w\\.]*?uploady\\.to/dl/((\\?d|download\\.php\\?id)=[A-Z0-9]+|((en|ru|fr|es)/)?file/[0-9]+/)", "http://(www\\.)?uploadstore\\.net/[a-z0-9]{12}", "http://[\\w\\.]*?vspace\\.cc/file/[A-Z0-9]+\\.html", "http://[\\w\\.]*?web-share\\.net/download/file/item/.*?_[0-9]+", "http://(www\\.)?yvh\\.cc/video\\.php\\?file=[a-z0-9_]+", "http://[\\w\\.]*?x-files\\.kz/[a-z0-9]+", "https?://(www\\.)?oteupload\\.com/((vid)?embed\\-)?[a-z0-9]{12}" }

)
public class Offline extends PluginForHost {

    /**
     * fullbuild help comment
     *
     * @param wrapper
     */
    public Offline(PluginWrapper wrapper) {
        super(wrapper);
    }

    @Override
    public Boolean siteTesterDisabled() {
        return true;
    }

    @Override
    public boolean checkLinks(DownloadLink[] urls) {
        if (urls != null) {
            for (final DownloadLink link : urls) {
                link.setAvailable(false);
            }
        }
        return true;
    }

    @Override
    public boolean isPremiumEnabled() {
        return false;
    }

    @Override
    public AccountInfo fetchAccountInfo(Account account) throws Exception {
        throw new PluginException(LinkStatus.ERROR_PREMIUM, "Permanently Offline: Host provider no longer exists", PluginException.VALUE_ID_PREMIUM_DISABLE);
    }

    @Override
    public String getAGBLink() {
        return null;
    }

    @Override
    public boolean isResumeable(DownloadLink link, Account account) {
        return false;
    }

    @Override
    public void handleFree(DownloadLink link) throws Exception {
        throw new PluginException(LinkStatus.ERROR_FILE_NOT_FOUND, "Permanently Offline: Host provider no longer exists");
    }

    @Override
    public AvailableStatus requestFileInformation(DownloadLink link) throws IOException, PluginException {
        throw new PluginException(LinkStatus.ERROR_FILE_NOT_FOUND, "Permanently Offline: Host provider no longer exists");
    }

    @Override
    public void reset() {
    }

    @Override
    public void resetDownloadlink(DownloadLink link) {
    }

    /* NO OVERRIDE!! We need to stay 0.9*compatible */
    public boolean hasCaptcha(DownloadLink link, jd.plugins.Account acc) {
        return false;
    }

}