package jd;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DDETimeUI.java
 *
 * Created on Nov 18, 2010, 9:10:29 PM
 */

/**
 * 
 * @author deek
 */
public class DDETimeUI extends javax.swing.JFrame {

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DDETimeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JScrollPane    PrimaryScrollPanel;

    private javax.swing.JMenuItem      createRecord;

    private javax.swing.JPanel         createRecordPanel;

    private javax.swing.JPanel         defaultPanel;

    private javax.swing.JMenuItem      generateReport;
    private javax.swing.JButton        jButton1;
    private javax.swing.JButton        jButton2;
    private javax.swing.JButton        jButton3;
    private javax.swing.JLabel         jLabel1;
    private javax.swing.JLabel         jLabel10;
    private javax.swing.JLabel         jLabel11;
    private javax.swing.JLabel         jLabel12;
    private javax.swing.JLabel         jLabel13;
    private javax.swing.JLabel         jLabel14;
    private javax.swing.JLabel         jLabel15;
    private javax.swing.JLabel         jLabel16;
    private javax.swing.JLabel         jLabel17;
    private javax.swing.JLabel         jLabel2;
    private javax.swing.JLabel         jLabel3;
    private javax.swing.JLabel         jLabel4;
    private javax.swing.JLabel         jLabel5;
    private javax.swing.JLabel         jLabel6;
    private javax.swing.JLabel         jLabel7;
    private javax.swing.JLabel         jLabel8;
    private javax.swing.JLabel         jLabel9;
    private javax.swing.JMenuBar       jLoggedMenu;
    private javax.swing.JMenu          jMenu1;
    private javax.swing.JMenu          jMenu2;
    private javax.swing.JMenu          jMenu3;
    private javax.swing.JMenu          jMenu4;
    private javax.swing.JMenu          jMenu5;
    private javax.swing.JMenuBar       jMenuBar1;
    private javax.swing.JMenuItem      jMenuItem1;
    private javax.swing.JMenuItem      jMenuItem2;
    private javax.swing.JScrollPane    jScrollPane1;
    private javax.swing.JTextArea      jTextArea1;
    private javax.swing.JTextField     jTextField1;
    private javax.swing.JTextField     jTextField10;
    private javax.swing.JTextField     jTextField11;
    private javax.swing.JTextField     jTextField2;
    private javax.swing.JTextField     jTextField3;
    private javax.swing.JTextField     jTextField4;
    private javax.swing.JTextField     jTextField5;
    private javax.swing.JTextField     jTextField6;
    private javax.swing.JTextField     jTextField7;
    private javax.swing.JTextField     jTextField8;
    private javax.swing.JTextField     jTextField9;
    private javax.swing.JPanel         loginPanel;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JMenuItem      searchRecords;
    private javax.swing.JTextField     userName;

    // End of variables declaration
    /** Creates new form DDETimeUI */
    public DDETimeUI() {
        initComponents();
    }

    private void createRecordMouseReleased(final java.awt.event.MouseEvent evt) {
        PrimaryScrollPanel.setViewportView(createRecordPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        createRecordPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        defaultPanel = new javax.swing.JPanel();
        jLoggedMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        createRecord = new javax.swing.JMenuItem();
        searchRecords = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        generateReport = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        PrimaryScrollPanel = new javax.swing.JScrollPane();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        passWord = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        createRecordPanel.setPreferredSize(new java.awt.Dimension(657, 368));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Record Name");

        jLabel4.setText("Time Code");

        jLabel5.setText("Assigner");

        jLabel6.setText("Start Date");

        jLabel7.setText("End Date");

        jLabel8.setText("Case Numbers");

        jLabel9.setText("Siebel");

        jLabel10.setText("Hydra");

        jLabel11.setText("QQ");

        jLabel12.setText("Maestro");

        jLabel13.setText("Hours");

        jLabel14.setText("Business");

        jLabel15.setText("Night");

        jLabel16.setText("Weekend");

        jLabel17.setText("Comments");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Submit");

        jButton2.setText("Cancel");

        final javax.swing.GroupLayout createRecordPanelLayout = new javax.swing.GroupLayout(createRecordPanel);
        createRecordPanel.setLayout(createRecordPanelLayout);
        createRecordPanelLayout.setHorizontalGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                createRecordPanelLayout
                        .createSequentialGroup()
                        .addGroup(
                                createRecordPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(createRecordPanelLayout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE).addComponent(jLabel8))
                                        .addComponent(jLabel17)
                                        .addGroup(
                                                createRecordPanelLayout
                                                        .createSequentialGroup()
                                                        .addGroup(
                                                                createRecordPanelLayout
                                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(
                                                                                createRecordPanelLayout.createSequentialGroup().addGap(25, 25, 25).addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel4).addComponent(jLabel5).addComponent(jLabel6).addComponent(jLabel7)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jTextField2).addComponent(jTextField3).addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE).addComponent(jTextField1)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                                                                        .addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel12).addComponent(jLabel11).addComponent(jLabel10).addComponent(jLabel9))).addGroup(javax.swing.GroupLayout.Alignment.LEADING, createRecordPanelLayout.createSequentialGroup().addGap(27, 27, 27).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(createRecordPanelLayout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE).addComponent(jTextField7).addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE).addComponent(jTextField5))).addGroup(createRecordPanelLayout.createSequentialGroup().addGap(24, 24, 24).addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jButton2).addComponent(jButton1)))))
                                        .addGroup(
                                                createRecordPanelLayout.createSequentialGroup()
                                                        .addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(javax.swing.GroupLayout.Alignment.LEADING, createRecordPanelLayout.createSequentialGroup().addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel16).addComponent(jLabel14).addComponent(jLabel15)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jTextField9).addComponent(jTextField11).addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))).addGroup(javax.swing.GroupLayout.Alignment.LEADING, createRecordPanelLayout.createSequentialGroup().addGap(82, 82, 82).addComponent(jLabel13)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE))).addContainerGap()));
        createRecordPanelLayout.setVerticalGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                createRecordPanelLayout.createSequentialGroup().addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(jLabel8)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel9).addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5).addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel10).addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6).addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel11).addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel7).addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel12).addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addComponent(jLabel13).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel14).addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel15).addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel16).addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel17).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(createRecordPanelLayout.createSequentialGroup().addComponent(jButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton2))).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        final javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 155, Short.MAX_VALUE));
        defaultPanelLayout.setVerticalGroup(defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 138, Short.MAX_VALUE));

        jMenu1.setText("File");
        jLoggedMenu.add(jMenu1);

        jMenu2.setText("Time");

        createRecord.setText("Create Record");
        createRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(final java.awt.event.MouseEvent evt) {
                createRecordMouseReleased(evt);
            }
        });
        jMenu2.add(createRecord);

        searchRecords.setText("Search Records");
        jMenu2.add(searchRecords);

        jLoggedMenu.add(jMenu2);

        jMenu3.setText("Reports");

        generateReport.setText("Generate Report");
        jMenu3.add(generateReport);

        jLoggedMenu.add(jMenu3);

        jMenu4.setText("Admin");

        jMenuItem1.setText("Build Workgroup");
        jMenu4.add(jMenuItem1);

        jLoggedMenu.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        jButton3.setText("Login");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(final java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });

        final javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(loginPanelLayout.createSequentialGroup().addGap(81, 81, 81).addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(loginPanelLayout.createSequentialGroup().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(loginPanelLayout.createSequentialGroup().addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jButton3).addComponent(passWord)))).addContainerGap(137, Short.MAX_VALUE)));
        loginPanelLayout.setVerticalGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(loginPanelLayout.createSequentialGroup().addGap(83, 83, 83).addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(passWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addComponent(jButton3).addContainerGap(107, Short.MAX_VALUE)));

        PrimaryScrollPanel.setViewportView(loginPanel);

        jMenu5.setText("File");

        jMenuItem2.setText("Log-In");
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(PrimaryScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(PrimaryScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE));

        pack();
    }// </editor-fold>

    private void jButton3MouseReleased(final java.awt.event.MouseEvent evt) {
        PrimaryScrollPanel.setViewportView(defaultPanel);
        setJMenuBar(jLoggedMenu);
        // repaint();

    }

}
